import {readFile,writeFile,access} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {modules,taskNotes,changes,scenarios} from './content.mjs';
import {glossary} from './glossary.mjs';
const here=dirname(fileURLToPath(import.meta.url));
const root=resolve(here,'../..');
const snapshot=JSON.parse(await readFile(resolve(here,'status-snapshot.json'),'utf8'));
const css=await readFile(resolve(here,'review.css'),'utf8');
const js=await readFile(resolve(here,'review.js'),'utf8');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const m of modules)m.files=m.files.map(p=>p==='runtime/src/infrastructure/file-state.ts'?'runtime/src/infrastructure/file-journal-state.ts':p);
for(const p of [...new Set(modules.flatMap(m=>[...m.files,...m.docs]))])await access(resolve(root,p));
const term=(id,label)=>`<button class="term" type="button" data-term="${esc(id)}" aria-label="${esc(label||glossary.find(t=>t.id===id)?.en||id)} 용어 설명">${esc(label||id)}</button>`;
const labels={local:'로컬 검증',partial:'부분 구현',review:'구현·설계 검토',planned:'계획 단계',verified:'범위 완료',in_progress:'진행 중',not_started:'미착수',conditional_not_started:'조건부'};
const badge=s=>`<span class="badge ${s}">${labels[s]}</span>`;
const link=(p,label)=>`<a href="../${esc(p)}" target="_blank" rel="noopener">${esc(label||p.split('/').at(-1))}</a>`;
const sources=paths=>`<div class="source-row">${paths.filter(Boolean).map(p=>link(p)).join(' · ')}</div>`;
const moduleButton=(id,label,extra='')=>`<button type="button" class="node ${extra}" data-module="${id}">${esc(label||modules.find(m=>m.id===id).name)}<small>${esc(modules.find(m=>m.id===id).en)}</small></button>`;
const stats=snapshot.counts;
const nav=[['overview','한눈에 보기'],['architecture','전체 구조'],['flow','한 업무의 흐름'],['modules','기능별 구현'],['methods','동작·개발 방법론'],['roadmap','계획과 남은 일'],['review','이번에 검토할 변경'],['glossary','용어 사전']];
const phaseShort={P0:'기준·계약',P1:'기본 실행',P2:'기억·효율',P3:'도구·화면',P4:'역할 협업',P5:'업무 배치',P6:'운영·시범'};
const phaseDescriptions={P0:'두 업무군의 기준 자료와 계약, TS/저장소 선택을 마련했다.',P1:'최소 코어는 구현됐다. 실제 모델의 계획 품질과 전체 업무 검증이 남았다.',P2:'기억·문맥·도구 효율·모드·자원·권한의 로컬 계약을 검증했다.',P3:'로컬 MCP·CLI/Web·계측 Web 조작은 구현됐다. 사내 MCP·Knox와 통합 검증이 남았다.',P4:'게시판·요청·알림·자원 배정 기반은 구현됐다. 현재 역할/권한 결합을 검토하고 있다.',P5:'업무별 배치 묶음과 도구·지침 변경의 검토/되돌리기를 만들 단계다.',P6:'운영 복원·용량·제한 시범을 거쳐 실제 도입을 판단할 단계다.'};
const overview=`<section class="view" id="overview" aria-labelledby="overview-title">
<div class="overview-hero"><div><div class="eyebrow">SECUMON / PROJECT REVIEW</div><h1 id="overview-title">무엇을 만들었고,<br>어디까지 왔을까.</h1><p class="lead">시큐몬을 참고해 만드는 <strong>범용 롱 호라이즌 에이전트</strong>.<br>오래 걸리는 업무의 목표·근거·진행을 남기며 이어가는 체계다.</p></div><div class="hero-aside"><span class="badge review">지금은 검토 시간</span><strong>기반을 확인하고<br>다음 방향을 정리한다.</strong><p>제품 구현의 추가 변경은 보류 중이다. 이 페이지는 현재 코드와 검증 기록을 읽어 만든 안내서다.</p></div></div>
<div class="count-block" aria-label="31개 계획 항목의 상태"><div class="stat"><div class="stat-value">${stats.verified}<small> / 31</small></div><div class="stat-label">정한 범위 완료</div><div class="stat-sub">P0 4개 · P1 5개</div></div><div class="stat"><div class="stat-value">${stats.in_progress}</div><div class="stat-label">구현 진행·추가 검증 필요</div><div class="stat-sub">로컬 검증을 포함한다</div></div><div class="stat"><div class="stat-value">${stats.not_started}</div><div class="stat-label">본 구현 미착수</div><div class="stat-sub">연동·협업·배치·운영</div></div><div class="stat"><div class="stat-value">${stats.conditional_not_started}</div><div class="stat-label">필요하면 수행</div><div class="stat-sub">기존 진행 업무 이관</div></div></div>
<p class="fine">항목의 크기가 다르므로 9/31을 제품 완성률로 보지 않는다. ‘진행 중’에는 상당한 로컬 구현과 검증이 끝난 항목도 있다.</p>
<div class="two gap-top"><div class="overview-map"><div class="eyebrow">핵심 구조</div><h3>대화가 끊겨도,<br>업무는 상태로 이어진다.</h3><div class="map-line"><span class="map-box">사람의 요청</span><span class="map-arrow">→</span><span class="map-box strong">업무 상태 + 추론 루프</span><span class="map-arrow">→</span><span class="map-box">검증된 결과</span></div><p class="fine">계획 · 가설 · 실행 · 근거 · 재계획<br>아래에는 저장소, 옆에는 도구와 동료 역할이 연결된다.</p><a href="#architecture" class="gap-top" style="display:inline-block;font-size:12px">전체 구조 살펴보기 →</a></div><div><h3>지금 할 수 있는 것의 범위</h3><ul class="fact-list"><li>고정 모델 대역으로 계획·실행·근거·재개 흐름 검증</li><li>원본을 보존하며 문맥·도구·기억을 선택 조회</li><li>두 저장소, 로컬 MCP·Web·컴퓨터 유즈 경계 검증</li><li>게시판 요청·알림과 작업별 자원 정산 기반</li></ul><div class="note warm gap-top"><strong>아직 확인하지 않은 것</strong><br>실제 사내 모델의 추론 능력, 사내 MCP·Knox 연동, 상시 자율 협업, 운영 배포.</div></div></div>
<div class="evidence-ribbon"><div><b>2,460 / 2,460</b> 현재 소스의 전체 검사 통과<br><span class="fine">2026.09.06 19:43 KST · 신규 관련 44개 포함 · 실제 모델 시험 아님</span></div><a href="#methods">검증의 의미 보기 →</a></div>
<div class="gap-top"><div class="row between"><h3>전체 여정에서의 위치</h3><a href="#roadmap" class="fine">31개 항목 보기 →</a></div><div class="phase-mini">${snapshot.phases.map(p=>`<a href="#roadmap" data-phase-link="${p.id}" class="${p.derivedStatus==='verified'?'finished':p.derivedStatus==='in_progress'?'started':''}"><b>${p.id}</b><span>${phaseShort[p.id]}</span></a>`).join('')}</div></div>
<div class="note gap-top"><strong>먼저 기억할 한 가지.</strong> 고정 리드–워커 조직을 채택한 구조가 아니다. 현재 구현된 <em>작업별 자원 위임</em>과 앞으로 구성할 <em>에이전트 협업 관계</em>는 구분해서 검토한다.</div></section>`;
const architecture=`<section class="view" id="architecture" aria-labelledby="architecture-title"><div class="section-head"><div class="eyebrow">01 / STRUCTURE</div><h2 id="architecture-title">같은 코어, 필요한 역할과 연결</h2><p>아래 상자는 논리적 책임이다. 상자마다 별도 모델이나 서버를 만드는 것은 아니다. 항목을 누르면 실제 구현과 남은 범위가 열린다.</p></div>
<div class="arch-stack"><div class="arch-layer"><div class="arch-layer-label">사람과 만나는 곳<small>입력·표시·전달</small></div><div><div class="arch-tiles">${moduleButton('channels','CLI · Web · Knox')}${moduleButton('channels','사람과 대화하는 역할')}</div><p class="arch-note">CLI/Web은 로컬 검증, Knox는 미착수. 대화 담당도 공통 runtime을 사용하는 역할이며 필수 상위 리드가 아니다.</p></div></div>
<div class="arch-layer"><div class="arch-layer-label">업무를 이어가는 곳<small>공통 실행 코어</small></div><div><div class="arch-tiles">${moduleButton('work','목표와 상태','accent')}${moduleButton('plan','계획·가설·검증','accent')}${moduleButton('execute','실행·근거·완료','accent')}${moduleButton('modes','모드·진척 제어','accent')}</div><p class="arch-note">계속 진행 / 재계획 / 대기 / 완료 판단이 저장된 상태를 중심으로 반복된다.</p></div></div>
<div class="arch-layer"><div class="arch-layer-label">현재 필요한 재료<small>선택해서 읽기</small></div><div class="arch-tiles">${moduleButton('context','문맥·compact')}${moduleButton('memory','기억·근거·작업 파일')}${moduleButton('guidance','스킬·방법론')}</div></div>
<div class="arch-layer"><div class="arch-layer-label">실제로 일을 하는 수단<small>도구와 adapter</small></div><div class="arch-tiles">${moduleButton('tools','도구 목록·호출')}${moduleButton('mcp','기존 MCP 연결')}${moduleButton('computer','컴퓨터 유즈')}</div></div>
<div class="arch-layer"><div class="arch-layer-label">협업과 자원<small>업무별 관계</small></div><div><div class="arch-tiles">${moduleButton('board','게시판·요청·알림')}${moduleButton('budget','배정·정산·반환')}${moduleButton('future','A2A · 상시 임무')}</div><p class="arch-note">게시판/자원 기반은 부분 구현. 동료의 상시 실행·미응답 처리·자율 협업은 남아 있다.</p></div></div>
<div class="arch-layer"><div class="arch-layer-label">모든 경로의 기반<small>보존·복구·권한</small></div><div class="arch-tiles">${moduleButton('storage','저장소 포트 · 두 adapter')}${moduleButton('policy','현재 권한·출처 확인')}</div></div></div>
<div class="three gap-top"><div class="principle"><b>조직도 ≠ 자원 장부</b><p>부모/자식 작업은 비용을 나누는 관계다. 에이전트의 영구적인 계급을 뜻하지 않는다.</p></div><div class="principle"><b>역할 ≠ 모델 위치</b><p>요청·조사·검토·대화 모두 사내 모델을 쓸 수 있게 한다. 실제 연결은 아직 미검증이다.</p></div><div class="principle"><b>코어 ≠ 저장 제품</b><p>코어는 저장 약속을 사용한다. SQLite/파일 저널을 시험했고 PostgreSQL에 고정하지 않았다.</p></div></div>
<div class="note gap-top">현재 제품 언어는 ${term('TypeScript','TypeScript + Node.js')}. Rust는 필요성이 확인되면 검토할 선택지이며, 기존 Python 실행 코드를 코어의 필수 의존성으로 두지 않는다.</div></section>`;
const flow=`<section class="view" id="flow" aria-labelledby="flow-title"><div class="section-head"><div class="eyebrow">02 / LONG HORIZON</div><h2 id="flow-title">한 업무가 끝날 때까지</h2><p>버튼으로 상황과 단계를 바꿔 보자. 아래는 구조를 이해하기 위한 설명용 예시다. 실제 모델이나 도구를 호출하지 않는다.</p></div>
<div class="segmented" role="group" aria-label="실행 상황 선택">${Object.entries(scenarios).map(([key,s],i)=>`<button type="button" class="seg" data-scenario="${key}" aria-pressed="${i===0}">${s.label}</button>`).join('')}</div><p id="scenario-intro" class="muted">${scenarios.normal.intro}</p>
<div class="flow-layout"><div class="flow-steps" id="flow-steps" aria-label="실행 단계"></div><div class="story" aria-live="polite"><div class="story-count" id="story-count">01 / 08</div><h3 id="story-title">요청 저장</h3><p id="story-main" class="story-main"></p><p id="story-note" class="story-note"></p><div class="row between"><button type="button" class="btn" id="step-prev">← 이전</button><button type="button" class="btn primary" id="step-next">다음 단계 →</button></div></div></div>
<div class="note gap-top">${term('goal','목표(goal)')}는 무엇을 끝내야 하는지, ${term('state','상태(state)')}는 어디까지 진행됐는지다. ${term('hypothesis','가설')}은 검증할 생각, ${term('evidence','근거')}는 그 생각을 지지하거나 반박할 관측이다. ${term('taskGraph','작업 관계도(task graph)')}는 확인할 일을 실행 순서로 연결한다.</div>
<div class="mini-compare"><h3>항상 오래 생각해야 할까?</h3><div class="three gap-top"><div class="mode-card"><b>빠르게 <code>fast</code></b><p>간단한 업무를 좁은 범위에서 처리한다. 제한에 닿았다고 목표 완료로 표시하지 않는다.</p></div><div class="mode-card"><b>자동 <code>auto</code></b><p>직접 처리로 시작하고 반증·복잡성이 있으면 허용 범위 안에서 조사 전략으로 확장한다.</p></div><div class="mode-card"><b>깊게 <code>deep</code></b><p>조사 전략으로 시작한다. 충분한 근거가 있으면 불필요한 추가 호출 없이 종료할 수 있다.</p></div></div><p class="fine gap-top">모드의 실행 규칙은 로컬 검증했다. 실제 모델의 최적 기본값·속도·정확도는 아직 측정하지 않았다.</p></div>
<hr class="rule"><h3>문맥을 정리해도 업무는 사라지지 않는다</h3><p class="muted gap-top" style="font-size:14px">${term('compact','compact')}는 책상 위 자료를 정리하는 것에 가깝다. 정본 상태와 원본은 보관한다.</p><div class="workspace-demo"><div class="desk"><div class="save-label">이번 모델 입력 · 책상</div><span class="paper-strip">목표 · 완료 조건 · 미완료 의무</span><span class="paper-strip">현재 가설 · 핵심 근거 · 실행 중 작업</span><span class="paper-strip optional" id="unused-tool">오랫동안 쓰지 않은 도구 설명</span><span class="paper-strip optional" id="old-result">이미 끝난 조사 결과의 긴 본문</span></div><div class="archive"><div class="save-label">저장소 · 보관함</div><p style="font-size:14px">전체 업무 상태 · 원 응답 · 호출 기록 · 출처 관계 · 작업 파일</p><p class="fine gap-top" id="archive-note">정리 전에도 원본은 이곳에 저장돼 있다.</p></div></div><div class="row"><button type="button" class="btn" id="compact-demo">문맥 정리 예시 보기</button><span class="fine" id="compact-caption" aria-live="polite">설명용 표시 전환이며 실제 자료는 수정하지 않는다.</span></div></section>`;
const modulesView=`<section class="view" id="modules" aria-labelledby="modules-title"><div class="section-head"><div class="eyebrow">03 / IMPLEMENTATION</div><h2 id="modules-title">기능을 누르면, 구현 내용이 보인다</h2><p>16개 기능 묶음으로 정리했다. 상태 표시는 로컬 검증 범위다. 정식 계획 항목 31개의 상태는 ‘계획과 남은 일’에서 별도로 볼 수 있다.</p></div><div class="filters"><label class="field grow">기능 검색<input id="module-search" type="search" placeholder="예: 가설, memory, 게시판"></label><label class="field">분야<select id="module-filter"><option value="all">전체 분야</option><option value="core">핵심 실행</option><option value="context">문맥·기억</option><option value="tools">도구·방법</option><option value="collaboration">협업·자원</option><option value="platform">저장·채널·배치</option></select></label></div><p class="fine" id="module-count" aria-live="polite">16개 기능</p><div class="module-grid gap-top">${modules.map(m=>`<article class="module" data-module-card="${m.id}" data-group="${m.group}"><div class="row between"><h3>${esc(m.name)}</h3>${badge(m.status)}</div><div class="module-en">${esc(m.en)}</div><p>${esc(m.summary)}</p><button type="button" class="btn small" data-module="${m.id}" aria-label="${esc(m.name)} 구현 내용 보기">구현·남은 일 보기 ↗</button></article>`).join('')}</div><p class="empty" id="module-empty" hidden>조건에 맞는 기능이 없다. 검색어나 분야를 바꿔 보자.</p></section>`;
const methods=`<section class="view" id="methods" aria-labelledby="methods-title"><div class="section-head"><div class="eyebrow">04 / HOW WE WORK</div><h2 id="methods-title">만드는 방법과, 일하는 방법</h2><p>개발 과정의 방법론과 완성될 에이전트가 업무를 수행하는 방법론을 구분해서 읽으면 이해가 쉽다.</p></div>
<h3>우리가 코어를 개발해 온 순서</h3><div class="method-track">${[['01','개념','무엇을 해결하고 어떤 의미를 지킬지 정한다.'],['02','계획·판정 기준','정상·실패·복구에서 기대할 결과를 구체화한다.'],['03','작은 단위 구현','공통 계약을 유지하며 한 실행 경로를 연결한다.'],['04','실행·검증','기능 시험과 기존 경로의 회귀 검사를 수행한다.'],['05','결과·결정 저장','성공·실패·한계·다음 작업을 파일로 남긴다.']].map(([n,t,d])=>`<div class="method-step"><span>${n}</span><b>${t}</b><p>${d}</p></div>`).join('')}</div><div class="note">스킬을 형식적으로 호출하는 절차는 필수가 아니다. 필요한 지침만 사용한다. 현재는 사용자의 요청으로 구현 변경을 멈추고 수정 범위와 현황을 검토한다.</div>
<hr class="rule"><h3>에이전트가 업무를 수행할 때의 방법</h3>${[['01','필요한 만큼 계획한다','간단한 일은 짧게, 불확실성이 크면 경쟁 가설과 판별 질문을 만든다. 모든 기능마다 별도 모델을 호출하지 않는다.'],['02','필요한 도구·기억·지침을 찾는다','후보 검색 → 정확한 형식 조회 → 현재 권한/버전 검사 → 호출. 사용한 결과가 유효하면 재사용한다.'],['03','근거가 바뀌면 판단을 갱신한다','새 증거와 반증을 기존 가설에 연결한다. 필요한 작업만 수정하고 끝난 일을 무조건 반복하지 않는다.'],['04','불명확하면 기록을 보존한다','확인되지 않은 효과나 사용량을 0 또는 성공으로 바꾸지 않는다. 응답이 저장돼 있으면 원본을 재사용해 복구한다.'],['05','완료와 전달까지 확인한다','명령 실행, 결과 채택, 목표 충족, 사용자 전달을 서로 다른 상태로 관리한다.']].map(([n,t,d])=>`<div class="method-point"><span class="num">${n}</span><div><h4>${t}</h4><p>${d}</p></div></div>`).join('')}
<div class="two gap-top"><div class="panel"><div class="eyebrow">자원 장부 예시</div><h3>8회를 배정하고 3회를 썼다면?</h3><p class="fine gap-top">전체 도구 호출 몫 20회. 아래 숫자는 설명용이며 현재 프로젝트의 사용량이 아니다.</p><div class="budget-bars" id="budget-bars" aria-label="20회 몫의 배정 상태"></div><div class="legend"><span><i style="background:#dce4df"></i>가용</span><span><i style="background:#d8b878"></i>예약·보류</span><span><i style="background:#4b7f6e"></i>사용 확정</span></div><p class="budget-caption" id="budget-caption" aria-live="polite"></p><div class="row"><button class="btn small" type="button" data-budget="allocate">8회 배정</button><button class="btn small" type="button" data-budget="settle">3회 사용 후 정산</button><button class="btn small" type="button" data-budget="unknown">사용량 불명</button></div><p class="fine gap-top">배정·정산 기반은 구현됨. 에이전트가 이 숫자를 직접 결정하는 조회/조정 도구 연결은 남아 있다.</p></div><div class="panel"><div class="eyebrow">채팅 표시 예시</div><h3>사람에게 필요한 변화만</h3><div class="chat-example"><div class="bubble person">두 문서의 최신 기준을 확인해 줘.</div><div class="bubble">요청을 접수했어. 문서와 개정 이력을 확인할게.</div><div class="task-bubble"><b>문서 검토 · 진행 중</b>근거 1개 확인 / 추가 자료 확인 중</div><div class="bubble">현재 기준은 30일이야. 이전 90일 문서는 개정됐어. 근거와 확인 범위를 함께 정리했어.</div></div><p class="fine gap-top">표시 방식의 설명 예시다. 로컬 CLI/Web 경로는 검증했고 Knox는 미연결이다.</p></div></div>
<hr class="rule"><h3>‘검증 통과’가 말해 주는 범위</h3><div class="table-wrap gap-top"><table class="comparison"><thead><tr><th>확인한 것</th><th>의미</th><th>아직 말할 수 없는 것</th></tr></thead><tbody><tr><td>전체 검사 2,460개</td><td>현재 소스의 정상·실패·복구 기대가 통과했다.</td><td>실제 모델의 문제 해결 능력이나 제품 완성도</td></tr><tr><td>고정 모델 대역</td><td>미리 정한 제안에 코어가 올바르게 반응한다.</td><td>실제 모델이 좋은 가설과 계획을 만드는지</td></tr><tr><td>로컬 MCP / Web</td><td>실제 로컬 프로토콜과 계측 화면의 경로가 동작한다.</td><td>사내 인증·Knox·임의 사이트/OS 동작</td></tr><tr><td>저장소·프로세스 복구</td><td>시험한 중단 지점에서 원본과 진행을 보존한다.</td><td>분산 운영·재해 복구·무제한 장기 실행 보장</td></tr></tbody></table></div><p class="fine gap-top">최신 전체 실행: 2026.09.06 19:43 KST 종료, 실패·취소·건너뜀 0. 코어 타입 검사, 계층 검사 124파일/위반 0, 합성 기준선 4개/22판정 통과. 별도 lint 명령은 구성되지 않았다. 신규 44개는 전체 2,460개에 포함된다.</p><details class="gap-top"><summary style="cursor:pointer;font-size:13px">실행 기록과 현재 소스 확인 근거</summary><div class="note gap-top"><p class="fine">기존 상태 문서는 v0.50 기준이다. 이 안내서는 이후 종료된 전체 검증 로그와 현재 빌드의 일치를 확인해 반영했다. 제품 상태 승격이나 이전 자동 정리 스크립트 실행은 하지 않았다.</p><span class="source-path">sourceDigest: ${snapshot.verification.build.sourceDigest}</span>${sources(['runtime/evidence/P4-board-funding-verify1-exit.json','runtime/evidence/P4-board-funding-verify1.log','runtime/evidence/P4-board-funding-new1-exit.json','design/review/status-snapshot.json'])}</div></details></section>`;
const roadmap=`<section class="view" id="roadmap" aria-labelledby="roadmap-title"><div class="section-head"><div class="eyebrow">05 / ROADMAP</div><h2 id="roadmap-title">전체 계획과, 아직 남은 일</h2><p>계획 항목 31개를 단계별로 본다. ‘진행 중’이라고 해서 구현이 없는 것은 아니다. 항목을 펼치면 현재 결과와 남은 조건을 함께 볼 수 있다.</p></div>
<div>${snapshot.phases.map(p=>{const items=snapshot.items.filter(i=>i.phase===p.id);const done=items.filter(i=>i.status==='verified').length;const active=items.filter(i=>i.status==='in_progress').length;return `<div class="road-phase"><div class="phase-code">${p.id}</div><div><h3>${esc(p.title)}</h3><p>${phaseDescriptions[p.id]}</p><span class="fine">${items.length}개 항목 · 완료 ${done} · 진행 ${active}</span></div>${badge(p.derivedStatus)}</div>`}).join('')}</div>
<div class="note gap-top"><strong>지금 다음 행동은 ‘설계 검토’다.</strong> 검토 후에는 역할·자료·자원 관계를 정리하고, 에이전트의 자원 관리 도구와 담당 역할 실행을 연결한다. 사내 모델/API 시험은 계속 중단 상태이며 자동 재개하지 않는다.</div>
<hr class="rule"><div class="row between"><h3>31개 구현 항목</h3><span class="fine" id="work-count" aria-live="polite">31개 표시</span></div><div class="filters"><label class="field grow">항목 검색<input id="work-search" type="search" placeholder="예: 저장, P4, Knox"></label><label class="field">단계<select id="work-phase"><option value="all">전체 단계</option>${snapshot.phases.map(p=>`<option value="${p.id}">${p.id} ${phaseShort[p.id]}</option>`).join('')}</select></label><label class="field">상태<select id="work-status"><option value="all">전체 상태</option><option value="verified">범위 완료</option><option value="in_progress">진행 중</option><option value="not_started">미착수</option><option value="conditional_not_started">조건부</option></select></label><button type="button" class="btn" id="work-reset">초기화</button></div>
<div class="work-list">${snapshot.items.map(w=>`<details class="work-card" id="item-${w.id}" data-phase="${w.phase}" data-status="${w.status}"><summary><span class="work-id">${w.id}</span><span class="work-title">${esc(w.title)}</span>${badge(w.status)}</summary><div class="work-content"><div><b>${w.status.includes('not_started')?'현재 계획·기반':'현재 구현·확인'}</b>${esc(taskNotes[w.id][0])}</div><div><b>남은 범위·해석</b>${esc(taskNotes[w.id][1])}</div>${sources([w.id==='P4-01'?'design/chapters/P4-board-funding-result.md':w.document,w.record])}</div></details>`).join('')}</div><p class="empty" id="work-empty" hidden>조건에 맞는 항목이 없다. 검색이나 필터를 초기화해 보자.</p><p class="fine gap-top">단계 상태는 하위 항목으로 계산했다. 원 작업 목록의 P4 단계 표기와 일부 funding 필드는 갱신 전이므로, 최신 실행 기록과 개별 구현을 우선해 설명했다. 원 작업 목록 자체의 완료 상태는 변경하지 않았다.</p></section>`;
const review=`<section class="view" id="review" aria-labelledby="review-title"><div class="section-head"><div class="eyebrow">06 / DESIGN REVIEW</div><h2 id="review-title">이번에 멈춰서 확인할 부분</h2><p>기반 코어를 유지하면서, 최근 협업·자료·자원 연결부의 제약을 검토한다. 아래 변경은 제안 또는 확인할 기준이며 구현 적용 완료가 아니다.</p></div><div class="note warm"><strong>확인된 사용자 방향</strong><br>범용 에이전트 · 고정 리드–워커 강제 없음 · 모든 역할의 사내 모델 사용 가능 · 과도하게 복잡한 게시판 흐름 재검토 · 수정 내용을 정리한 뒤 다음 구현.</div>
<div class="table-wrap gap-top"><table class="comparison"><thead><tr><th>항목</th><th>유지할 기반</th><th>수정·검토할 내용</th></tr></thead><tbody>${changes.map(row=>`<tr>${row.map(s=>`<td>${esc(s)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>
<div class="two gap-top"><div class="panel"><h3>네 가지 관계를 분리한다</h3><ul class="fact-list"><li>협업: 누가 누구에게 질문하고 답하는가</li><li>자원: 어느 작업이 비용을 부담하는가</li><li>권한: 누가 어떤 자료를 읽고 전달하는가</li><li>모델: 어느 실행 환경에서 추론하는가</li></ul></div><div class="panel"><h3>아직 열어 둔 선택</h3><ul class="fact-list"><li>게시판의 공유 범위와 원문 접근 정책</li><li>강한 격리가 필요한 배치의 공개 절차</li><li>수락 판단에 쓸 자원의 소유 방식</li><li>조정자와 미응답 재배정의 최소 실행 정책</li></ul></div></div>
<div class="note gap-top">원래 설계도 고정 리드 계층을 강제하지 않았다. 이번에는 특정 요청의 지원/수행 관계가 모든 협업의 조직도나 자료 권한으로 굳어지지 않게 점검한다.</div><h3 class="gap-top">검토가 끝난 뒤의 작은 구현 순서</h3><ol style="font-size:14px;padding-left:22px"><li>역할·모델·자료·자원의 관계와 기본 협업 사례를 정한다.</li><li>현재 코드에서 영향을 받는 연결부를 확인한다.</li><li>독립 역할의 요청·응답부터 작은 단위로 연결한다.</li><li>자원 조정·미응답 처리·선택 격리를 확장하고 회귀 검증한다.</li></ol>${sources(['design/chapters/P4-design-reconciliation.md','design/chapters/P4-shared-board-simplification.md','design/05-data-boundary-options.md'])}
</section>`;
const glossaryView=`<section class="view" id="glossary" aria-labelledby="glossary-title"><div class="section-head"><div class="eyebrow">07 / GLOSSARY</div><h2 id="glossary-title">코드 용어를 일의 언어로</h2><p>이름과 변수는 일을 구분하기 위한 표지다. 영문 이름과 쉬운 설명, 구체적인 예시를 함께 읽어 보자. 본문의 초록색 점선 용어도 눌러 볼 수 있다.</p></div><div class="filters"><label class="field grow">용어 검색<input id="glossary-search" type="search" placeholder="예: state, 부모, 영수증, 모델"></label><span class="fine" id="glossary-count" aria-live="polite">${glossary.length}개 용어</span></div><div class="glossary-grid">${glossary.map(t=>`<article class="glossary-item" id="term-${t.id}" data-term-card="${t.id}"><h3>${esc(t.ko)}</h3><code>${esc(t.en)}</code><p>${esc(t.definition)}</p><p class="example">예 · ${esc(t.example)}</p><button class="btn small ghost" type="button" data-module="${t.module}">관련 구현 보기 →</button></article>`).join('')}</div><p class="empty" id="glossary-empty" hidden>찾는 용어가 없다. 한글 또는 영문 일부로 검색해 보자.</p></section>`;
const serial=JSON.stringify({modules,glossary,scenarios,items:snapshot.items.map(w=>({id:w.id,title:w.title})),snapshot:{asOf:snapshot.asOf}}).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
const html=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><meta name="description" content="범용 롱 호라이즌 에이전트의 개념, 구조, 구현 현황과 남은 작업을 정리한 로컬 검토 안내서"><title>시큐몬 · 구현 현황 안내서</title><style>${css}</style></head><body><a class="skip" href="#main">본문으로 이동</a><aside class="sidebar"><a href="#overview" class="brand"><span class="brand-mark">S</span> secumon</a><div class="brand-sub">범용 에이전트 · 구현 현황 안내서</div><div class="nav-group-label">REVIEW GUIDE</div><nav aria-label="안내서 목차">${nav.map(([id,label],i)=>`<a class="nav-link" href="#${id}" ${i===0?'aria-current="page"':''}><span>0${i}</span>${label}</a>`).join('')}</nav><div class="sidebar-foot"><span class="status-dot"></span>제품 변경 보류 · 검토 중<br>2026.09.06 상태 스냅샷<br>인터넷 없이 읽는 단일 HTML</div></aside><div class="shell"><header class="topbar"><span class="topbar-text">PROJECT NOTES <span style="margin:0 7px;color:#b0bbb5">/</span> <span id="view-name">한눈에 보기</span></span><div class="row"><button type="button" class="btn small" id="open-search" aria-label="전체 검색">검색 <span class="fine">⌘ K</span></button><button type="button" class="btn small" id="print-guide">인쇄 / PDF</button></div></header><main class="main" id="main">${overview}${architecture}${flow}${modulesView}${methods}${roadmap}${review}${glossaryView}<footer class="footer">이 안내서는 현재 프로젝트의 코드·계획·실행 기록을 바탕으로 작성한 정적 검토 자료다. 외부 네트워크 호출, 모델 호출, 원본 자료 변경은 하지 않는다. 용어 검색과 예시는 이 HTML 안에서만 동작한다.<br>내용 기준: 2026.09.06 · 최신 전체 검증 종료 19:43 KST · ${link('design/review/status-snapshot.json','상태 근거')} · ${link('design/chapters/P4-design-reconciliation.md','수정 범위 원문')}</footer></main></div>
<dialog class="dialog" id="module-dialog" aria-labelledby="module-title"><div class="dialog-head"><div><div class="eyebrow" id="module-en"></div><h3 id="module-title"></h3></div><button type="button" class="btn small" data-close="module-dialog" aria-label="구현 설명 닫기">닫기 ×</button></div><div class="dialog-body" id="module-body"></div></dialog>
<dialog class="dialog" id="term-dialog" aria-labelledby="term-title"><div class="dialog-head"><div><div class="eyebrow">TERM / 용어 설명</div><h3 id="term-title"></h3></div><button type="button" class="btn small" data-close="term-dialog" aria-label="용어 설명 닫기">닫기 ×</button></div><div class="dialog-body" id="term-body"></div></dialog>
<dialog class="dialog" id="search-dialog" aria-labelledby="search-title"><div class="dialog-head"><h3 id="search-title">안내서 전체 검색</h3><button type="button" class="btn small" data-close="search-dialog" aria-label="검색 닫기">닫기 ×</button></div><div class="dialog-body"><label class="field">기능·계획 항목·용어<input type="search" id="search-query" placeholder="예: compact, P4, 예산, Knox"></label><p id="search-count" class="fine gap-top" aria-live="polite"></p><div id="search-results" class="search-list"></div></div></dialog>
<script id="review-data" type="application/json">${serial}</script><script>${js}</script></body></html>`;
await writeFile(resolve(root,'design/secumon-review.html'),html);
console.log(JSON.stringify({output:'design/secumon-review.html',bytes:Buffer.byteLength(html),modules:modules.length,items:snapshot.items.length,glossary:glossary.length,sourceDigest:snapshot.verification.build.sourceDigest}));
