(()=>{'use strict';
const data=JSON.parse(document.getElementById('review-data').textContent);const $=id=>document.getElementById(id);const all=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusLabels={local:'로컬 검증',partial:'부분 구현',review:'구현·설계 검토',planned:'계획 단계'};
let currentView='overview',scenario='normal',step=0,compacted=false;const views=all('.view');
function showView(id,focus=false){if(!views.some(v=>v.id===id))id='overview';currentView=id;views.forEach(v=>v.hidden=v.id!==id);all('.nav-link').forEach(a=>{if(a.hash==='#'+id)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('view-name').textContent=document.querySelector('.nav-link[href="#'+id+'"]')?.textContent.replace(/^0\d/,'').trim()||'';if(focus){window.scrollTo(0,0);const h=$(id).querySelector('h2,h1');h.setAttribute('tabindex','-1');h.focus({preventScroll:true})}}
function route(){const hash=decodeURIComponent(location.hash.slice(1));if(hash.startsWith('item-')){showView('roadmap');resetWork();const el=$(hash);if(el){el.open=true;el.scrollIntoView({block:'center'})}}else if(hash.startsWith('term-')){showView('glossary');$('glossary-search').value='';filterGlossary();const el=$(hash);if(el)el.scrollIntoView({block:'center'})}else showView(hash||'overview')}
function navigate(id){if(location.hash==='#'+id)showView(id,true);else{location.hash=id;showView(id,true)}}
window.addEventListener('hashchange',route);
document.querySelector('.skip').addEventListener('click',e=>{e.preventDefault();$('main').setAttribute('tabindex','-1');$('main').focus();});
function openDialog(id){$(id).showModal();document.body.classList.add('body-lock')}
function closeDialog(id){$(id).close();if(!document.querySelector('dialog[open]'))document.body.classList.remove('body-lock')}
all('dialog').forEach(d=>{d.addEventListener('close',()=>{if(!document.querySelector('dialog[open]'))document.body.classList.remove('body-lock')});d.addEventListener('click',e=>{if(e.target===d)closeDialog(d.id)})});
function sourceLinks(paths){return paths.map(p=>'<a class="source-path" href="../'+esc(p)+'" target="_blank" rel="noopener">'+esc(p)+'</a>').join('')}
function openModule(id){const m=data.modules.find(m=>m.id===id);if(!m)return;$('module-title').textContent=m.name;$('module-en').textContent=m.en;$('module-body').innerHTML='<span class="badge '+m.status+'">'+statusLabels[m.status]+'</span><p class="gap-top">'+esc(m.summary)+'</p><h4>왜 필요한가</h4><p>'+esc(m.why)+'</p><h4>어떻게 동작하나</h4><ul>'+m.how.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul><h4>현재 구현·검증</h4><p>'+esc(m.done)+'</p><h4>남은 범위·한계</h4><p>'+esc(m.left)+'</p><div class="note gap-top"><strong>예를 들면</strong><br>'+esc(m.example)+'</div><div class="term-row">'+m.terms.map(id=>{const t=data.glossary.find(t=>t.id===id);return '<button type="button" class="term" data-term="'+id+'">'+esc(t.ko)+' · '+esc(t.en)+'</button>'}).join('')+'</div><details class="gap-top"><summary style="cursor:pointer;font-size:13px">구현 파일·결과 문서</summary><div class="gap-top">'+sourceLinks([...m.files,...m.docs])+'</div></details>';openDialog('module-dialog')}
function openTerm(id){const t=data.glossary.find(t=>t.id===id);if(!t)return;$('term-title').textContent=t.ko;$('term-body').innerHTML='<code>'+esc(t.en)+'</code><p class="gap-top">'+esc(t.definition)+'</p><div class="note gap-top">예 · '+esc(t.example)+'</div><div class="row gap-top"><button type="button" class="btn" data-term-goto="'+id+'">용어 사전에서 보기 →</button></div>';openDialog('term-dialog')}
document.addEventListener('click',e=>{const el=e.target.closest('button,a');if(!el)return;if(el.dataset.close){closeDialog(el.dataset.close)}else if(el.dataset.module){if($('search-dialog').open)closeDialog('search-dialog');if($('module-dialog').open)closeDialog('module-dialog');openModule(el.dataset.module)}else if(el.dataset.term){openTerm(el.dataset.term)}else if(el.dataset.termGoto){all('dialog[open]').forEach(d=>closeDialog(d.id));location.hash='term-'+el.dataset.termGoto;route()}else if(el.dataset.phaseLink){e.preventDefault();navigate('roadmap');$('work-phase').value=el.dataset.phaseLink;filterWork();$('work-phase').scrollIntoView({block:'center'})}else if(el.matches('.nav-link')){e.preventDefault();navigate(el.hash.slice(1))}});
function renderStory(){const s=data.scenarios[scenario];$('scenario-intro').textContent=s.intro;$('flow-steps').innerHTML=s.steps.map((v,i)=>'<button type="button" class="flow-step" data-step="'+i+'" '+(i===step?'aria-current="step"':'')+'><span>0'+(i+1)+'</span>'+esc(v[0])+'</button>').join('');$('story-count').textContent=String(step+1).padStart(2,'0')+' / '+String(s.steps.length).padStart(2,'0');$('story-title').textContent=s.steps[step][0];$('story-main').textContent=s.steps[step][1];$('story-note').textContent=s.steps[step][2];$('step-prev').disabled=step===0;$('step-next').disabled=step===s.steps.length-1;all('[data-scenario]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scenario===scenario)))}
all('[data-scenario]').forEach(b=>b.addEventListener('click',()=>{scenario=b.dataset.scenario;step=0;renderStory()}));$('flow-steps').addEventListener('click',e=>{const b=e.target.closest('[data-step]');if(b){step=Number(b.dataset.step);renderStory()}});$('step-prev').addEventListener('click',()=>{if(step>0){step--;renderStory()}});$('step-next').addEventListener('click',()=>{if(step<data.scenarios[scenario].steps.length-1){step++;renderStory()}});
$('compact-demo').addEventListener('click',()=>{compacted=!compacted;$('unused-tool').classList.toggle('removed',compacted);$('old-result').classList.toggle('removed',compacted);$('unused-tool').textContent=compacted?'미사용 도구 설명 → 필요할 때 다시 조회':'오랫동안 쓰지 않은 도구 설명';$('old-result').textContent=compacted?'과거 긴 본문 → 원본 참조로 보관':'이미 끝난 조사 결과의 긴 본문';$('archive-note').textContent=compacted?'원본과 정본 상태는 그대로. 발견/조회 도구로 필요한 내용을 다시 읽는다.':'정리 전에도 원본은 이곳에 저장돼 있다.';$('compact-caption').textContent=compacted?'현재 입력만 줄였다. 목표·의무·원본을 삭제하지 않는다.':'설명용 표시 전환이며 실제 자료는 수정하지 않는다.';$('compact-demo').textContent=compacted?'정리 전 모습 보기':'문맥 정리 예시 보기'});
function renderBudget(mode){const used=mode==='settle'?3:0;const held=mode==='allocate'||mode==='unknown'?8:0;$('budget-bars').innerHTML=Array.from({length:20},(_,i)=>'<span class="budget-unit '+(i<used?'used':i<used+held?'held':'')+'"></span>').join('');$('budget-bars').setAttribute('aria-label','가용 '+(20-used-held)+'회, 사용 확정 '+used+'회, 예약 또는 보류 '+held+'회');$('budget-caption').textContent=mode==='settle'?'종료·사용량 확인: 사용 3회, 미사용 5회 반환 → 가용 17회.':mode==='unknown'?'사용량 불명: 8회 몫을 보류 → 가용 12회. 0회 사용으로 가정해 반환하지 않는다.':'8회 몫을 배정·예약 → 배정한 쪽에서 바로 쓸 수 있는 몫은 12회.';all('[data-budget]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.budget===mode)))}all('[data-budget]').forEach(b=>b.addEventListener('click',()=>renderBudget(b.dataset.budget)));
function filterModules(){const q=$('module-search').value.toLocaleLowerCase().trim(),group=$('module-filter').value;let count=0;all('[data-module-card]').forEach(el=>{const m=data.modules.find(m=>m.id===el.dataset.moduleCard);const match=(!q||JSON.stringify(m).toLocaleLowerCase().includes(q))&&(group==='all'||m.group===group);el.hidden=!match;if(match)count++});$('module-count').textContent=count+' / '+data.modules.length+'개 기능';$('module-empty').hidden=count!==0}$('module-search').addEventListener('input',filterModules);$('module-filter').addEventListener('change',filterModules);
function filterWork(){const q=$('work-search').value.toLocaleLowerCase().trim(),phase=$('work-phase').value,status=$('work-status').value;let count=0;all('.work-card').forEach(el=>{const match=(!q||el.textContent.toLocaleLowerCase().includes(q))&&(phase==='all'||el.dataset.phase===phase)&&(status==='all'||el.dataset.status===status);el.hidden=!match;if(match)count++});$('work-count').textContent=count+' / 31개 표시';$('work-empty').hidden=count!==0}function resetWork(){$('work-search').value='';$('work-phase').value='all';$('work-status').value='all';filterWork()}['work-search','work-phase','work-status'].forEach(id=>$(id).addEventListener(id==='work-search'?'input':'change',filterWork));$('work-reset').addEventListener('click',resetWork);
function filterGlossary(){const q=$('glossary-search').value.toLocaleLowerCase().trim();let count=0;all('[data-term-card]').forEach(el=>{el.hidden=q!==''&&!el.textContent.toLocaleLowerCase().includes(q);if(!el.hidden)count++});$('glossary-count').textContent=count+' / '+data.glossary.length+'개 용어';$('glossary-empty').hidden=count!==0}$('glossary-search').addEventListener('input',filterGlossary);
function search(){const q=$('search-query').value.toLocaleLowerCase().trim();const entries=[...data.modules.map(m=>({kind:'module',id:m.id,label:m.name,sub:'기능 · '+m.en,search:JSON.stringify(m)})),...data.glossary.map(t=>({kind:'term',id:t.id,label:t.ko,sub:'용어 · '+t.en,search:JSON.stringify(t)})),...data.items.map(w=>({kind:'item',id:w.id,label:w.title,sub:'계획 · '+w.id,search:w.id+' '+w.title}))];const matches=q?entries.filter(x=>x.search.toLocaleLowerCase().includes(q)):entries.filter(x=>['context','plan','budget','board'].includes(x.id)&&x.kind==='module');$('search-count').textContent=q?matches.length+'개 결과 · 최대 30개 표시':'자주 찾는 기능';$('search-results').innerHTML=matches.slice(0,30).map(x=>'<button type="button" class="search-result" data-search-kind="'+x.kind+'" data-search-id="'+esc(x.id)+'">'+esc(x.label)+'<small>'+esc(x.sub)+'</small></button>').join('')||(q?'<p class="empty">검색 결과가 없다. 다른 말로 찾아 보자.</p>':'')}
function launchSearch(){search();openDialog('search-dialog');$('search-query').focus()}$('open-search').addEventListener('click',launchSearch);$('search-query').addEventListener('input',search);$('search-results').addEventListener('click',e=>{const b=e.target.closest('[data-search-kind]');if(!b)return;closeDialog('search-dialog');if(b.dataset.searchKind==='module')openModule(b.dataset.searchId);else if(b.dataset.searchKind==='term')openTerm(b.dataset.searchId);else{location.hash='item-'+b.dataset.searchId;route()}});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!$('search-dialog').open)launchSearch()}});
let printState=[];window.addEventListener('beforeprint',()=>{printState=all('details').map(el=>({el,open:el.open}));printState.forEach(x=>x.el.open=true)});window.addEventListener('afterprint',()=>{printState.forEach(x=>x.el.open=x.open);printState=[];showView(currentView)});$('print-guide').addEventListener('click',()=>window.print());
renderStory();renderBudget('allocate');filterModules();filterWork();filterGlossary();route();
})();
