apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../domains/smb
  - ../../domains/dev-web
  - ../../domains/github
  - ../../domains/confluence
  - ../../domains/jenkins
