apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: secu-agent-evidence
  namespace: secu-agent
  labels:
    app.kubernetes.io/part-of: secu-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
