"""v3.88 StatePort P1 — 신규 seam(port/adapter/orchestrator) 단위 검증.

register_schema=순수 메모리, connection(namespace)=SET LOCAL(신규 경로 public fallback 없음),
lazy 멱등 apply, finding 어댑터 위임.
"""
from __future__ import annotations

import psycopg
import pytest

import secu_agent.state as state
from secu_agent import persistence
from secu_agent.persistence import schema_orchestrator as orch
from secu_agent.persistence.postgres_adapter import default_state_port

NS = "skill_seamtest"
BASELINE = (
    "CREATE TABLE IF NOT EXISTS seam_probe ("
    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT);"
)


@pytest.fixture(autouse=True)
def _clean_registry():
    orch._reset_registry()
    state._SCHEMA_READY_NS.clear()
    yield
    orch._reset_registry()
    state._SCHEMA_READY_NS.clear()
    with state.connect() as c:
        rows = c.execute(
            "SELECT schema_name FROM information_schema.schemata "
            "WHERE substr(schema_name,1,11)='skill_seam'"
        ).fetchall()
        for r in rows:
            c.execute(f'DROP SCHEMA IF EXISTS "{r[0]}" CASCADE')


def test_namespace_allowlist():
    for bad in ("public", "skill_BAD", "core; DROP", "randstuff", ""):
        with pytest.raises(ValueError):
            persistence.validate_namespace(bad)
    for ok in ("core", "platform", "skill_smb", "skill_dev_web"):
        assert persistence.validate_namespace(ok) == ok


def test_register_schema_is_pure_memory():
    # 등록만으로 스키마/테이블이 생기면 안 됨 (DB 무접근).
    state.register_schema(NS, BASELINE)
    assert NS in orch.registered_namespaces()
    with state.connect() as c:
        got = c.execute(
            "SELECT 1 FROM information_schema.schemata WHERE schema_name=?", (NS,)
        ).fetchone()
        assert got is None  # 아직 CREATE 안 됨


def test_register_idempotent_and_conflict():
    state.register_schema(NS, BASELINE)
    state.register_schema(NS, BASELINE)  # 동일 checksum → no-op
    with pytest.raises(ValueError):
        state.register_schema(NS, BASELINE + "\nCREATE TABLE IF NOT EXISTS x(id BIGINT);")


def test_connection_applies_and_scopes():
    state.register_schema(NS, BASELINE)
    with state.connection(NS) as c:
        # search_path 는 skill_seamtest, platform, core (public 없음).
        path = c.execute("SHOW search_path").fetchone()[0].replace('"', "").replace(" ", "")
        assert path.split(",")[0] == NS and "public" not in path.split(",")
        # unqualified INSERT/SELECT 가 이 네임스페이스 테이블로 resolve.
        c.execute("INSERT INTO seam_probe(name) VALUES (?)", ("a",))
        row = c.execute("SELECT name FROM seam_probe WHERE name=?", ("a",)).fetchone()
        assert row is not None and row[0] == "a"
    # 테이블은 skill_seamtest 스키마에 생성됨.
    with state.connect() as c:
        sch = c.execute(
            "SELECT table_schema FROM information_schema.tables WHERE table_name='seam_probe'"
        ).fetchall()
        assert [r[0] for r in sch] == [NS]


def test_connection_unregistered_skill_fail_fast():
    with pytest.raises(LookupError):
        with state.connection("skill_seamtest_missing"):
            pass


# ── ensure_schema opt-out (migrator/runtime 권한 분리 토대) ────────────


def test_connection_ensure_schema_false_skips_apply(monkeypatch):
    """ensure_schema=False → apply_schema 미호출(spy). 등록 확인은 유지."""
    state.register_schema(NS, BASELINE)
    calls: list[str] = []
    monkeypatch.setattr(orch, "apply_schema", lambda ns: calls.append(ns))
    with state.connection(NS, ensure_schema=False) as c:
        # search_path 스코프는 그대로 걸린다(등록은 유효, DDL 만 스킵).
        assert c.execute("SELECT 1").fetchone()[0] == 1
    assert calls == []
    # 미등록 ns 는 ensure_schema 무관하게 여전히 LookupError.
    with pytest.raises(LookupError):
        with state.connection("skill_seamtest_missing", ensure_schema=False):
            pass
    assert calls == []


def test_connection_default_ensure_schema_applies(monkeypatch):
    """기본 ensure_schema=True 는 기존대로 apply_schema 를 호출한다(회귀 없음)."""
    state.register_schema(NS, BASELINE)
    calls: list[str] = []
    real = orch.apply_schema

    def spy(ns):
        calls.append(ns)
        return real(ns)

    monkeypatch.setattr(orch, "apply_schema", spy)
    with state.connection(NS) as c:  # ensure_schema 미지정 = True
        c.execute("INSERT INTO seam_probe(name) VALUES (?)", ("x",))
    assert calls == [NS]  # lazy provisioning 발동


def test_connection_ensure_schema_false_unprovisioned_is_clean_42P01(monkeypatch):
    """미provisioning + ensure_schema=False + skill 테이블 접근 → 깨끗한
    undefined_table(42P01). 실패한 CREATE 반복 없음."""
    np = "skill_seam_unprov"
    # 확실한 미provisioning: 등록(순수 메모리)만 하고 apply 는 하지 않는다.
    # (이전 테스트 잔재가 있어도 제거 — 스키마가 없어야 42P01 이 난다.)
    with state.connect() as c:
        c.execute(f'DROP SCHEMA IF EXISTS "{np}" CASCADE')
    state.register_schema(np, BASELINE)
    calls: list[str] = []
    monkeypatch.setattr(orch, "apply_schema", lambda ns: calls.append(ns))
    with pytest.raises(psycopg.Error) as ei:
        with state.connection(np, ensure_schema=False) as c:
            c.execute("SELECT * FROM seam_probe")
    assert ei.value.sqlstate == "42P01"  # undefined_table
    assert calls == []  # CREATE 재시도 없음(negative-cache 불요 — 애초에 안 만든다)


def test_connection_core_and_platform_always_available():
    with state.connection("core") as c:
        assert c.execute("SELECT 1").fetchone()[0] == 1
    with state.connection("platform") as c:
        assert c.execute("SELECT 1").fetchone()[0] == 1


def test_apply_is_idempotent_via_schema_version():
    state.register_schema(NS, BASELINE)
    orch.apply_schema(NS)
    orch.apply_schema(NS)  # 두 번째는 _SCHEMA_READY_NS fast-skip
    with state.connect() as c:
        n = c.execute(
            "SELECT count(*) FROM core.schema_version WHERE namespace=? AND phase='baseline'",
            (NS,),
        ).fetchone()[0]
        assert n == 1


def test_idless_tables_funnel():
    state.register_schema(NS, BASELINE, idless_tables=["seam_idless"])
    assert "seam_idless" in state._PG_IDLESS_TABLES


def test_finding_via_adapter_port():
    port = default_state_port()
    assert isinstance(port, persistence.StatePort)  # runtime_checkable Protocol
    fid, created = port.finding_upsert(
        task_type="t", asset="a", asset_kind="host", severity="high",
        summary="s", fingerprint="fp-adapter",
    )
    assert created and fid >= 1
    assert port.finding_get(fid)["summary"] == "s"
    assert any(f["id"] == fid for f in port.finding_list(status="open"))


def test_register_agent_type_accepts_role_types():
    # 계약 item6: register_agent_type 는 도메인만이 아니라 role 타입(hr/orchestrator/strategy)도 통과.
    from secu_agent import agent_type_registry as atr
    roles = ("hr", "orchestrator", "strategy")
    for r in roles:
        atr.register_agent_type(r)
    try:
        valid = atr.valid_agent_types()
        assert all(r in valid for r in roles)
    finally:
        for r in roles:
            atr.unregister_agent_type(r)


def test_validate_namespace_fullmatch_and_length():
    # codex: re.match($) 는 끝 개행 앞에서도 매치 → fullmatch 로 위장 식별자 차단.
    with pytest.raises(ValueError):
        persistence.validate_namespace("skill_x\n")
    with pytest.raises(ValueError):
        persistence.validate_namespace("skill_" + "a" * 70)  # >63


def test_register_schema_rejects_core_and_platform():
    for ns in ("core", "platform"):
        with pytest.raises(ValueError):
            state.register_schema(ns, "CREATE TABLE IF NOT EXISTS x(id BIGINT);")


def test_register_schema_rejects_bad_idless_ident():
    with pytest.raises(ValueError):
        state.register_schema(NS, BASELINE, idless_tables=["bad-name; DROP"])


def test_migration_applies_atomically_and_records():
    mig = "ALTER TABLE seam_probe ADD COLUMN IF NOT EXISTS extra TEXT;"
    state.register_schema(NS, BASELINE, migrations=[(1, mig)])
    orch.apply_schema(NS)
    with state.connect() as c:
        # migration 이 적용되고 core.schema_version 에 phase='migration',version=1 로 기록.
        rec = c.execute(
            "SELECT count(*) FROM core.schema_version "
            "WHERE namespace=? AND phase='migration' AND version=1",
            (NS,),
        ).fetchone()[0]
        assert rec == 1
    with state.connection(NS) as c:
        col = c.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name='seam_probe' AND column_name='extra'"
        ).fetchone()
        assert col is not None
