import { z } from 'zod';
import type { ComputerBinding, ComputerDriver } from '../application/computer-use-ports.js';
import { createComputerTools, prepareComputerBinding } from '../application/computer-use.js';
import { ComputerLimitsSchema } from '../application/computer-use-contracts.js';
import type { ToolDefinition } from '../application/ports.js';
import { frozen } from '../application/resource-contracts.js';
import { validProvider } from '../application/tool-contracts.js';

const text = (maximum: number) => z.string().min(1).max(maximum).refine(value => value.trim().length > 0 && !value.includes('\0'));
const MetadataSchema = z.strictObject({
  provider: text(100), id: text(256), version: text(256), description: text(10000), destination: text(256),
  labels: z.array(text(256)).max(100), sessionId: text(256), limits: ComputerLimitsSchema,
});
export interface CapturedHostComputerBindings {
  readonly bindings: readonly ComputerBinding[];
  /** Generated by the existing core factory; the host combines these with all other tool identities. */
  readonly definitions: readonly ToolDefinition[];
}
function invalid(cause?: unknown): Error {
  return new Error('agent_computer_registration_invalid', cause === undefined ? undefined : { cause });
}

/** Trusted host assembly only. Driver ownership and closing remain with the registration that supplied it. */
export function captureHostComputerBindings(input: readonly ComputerBinding[]): CapturedHostComputerBindings {
  try {
    if (!Array.isArray(input)) throw invalid();
    const bindings: ComputerBinding[] = [], definitions: ToolDefinition[] = [];
    const sessions = new Set<string>(), identities = new Set<string>(), objects = new WeakMap<ComputerDriver, Set<string>>();
    for (const candidate of Array.from(input)) {
      if (!candidate || typeof candidate !== 'object' || Array.isArray(candidate)) throw invalid();
      const { provider, id, version, description, destination, labels, sessionId, limits, driver } = candidate;
      if (!driver || typeof driver !== 'object' || Array.isArray(driver)) throw invalid();
      const metadata = MetadataSchema.parse(structuredClone({ provider, id, version, description, destination, labels, sessionId, limits }));
      if (!validProvider(metadata.provider) || metadata.provider === 'core' || metadata.id.startsWith('core.')) throw invalid();
      const binding = prepareComputerBinding({ ...metadata, driver });
      const session = JSON.stringify([binding.identity.id, binding.identity.version, binding.sessionId]);
      const ownedSessions = objects.get(driver) ?? new Set<string>();
      if (sessions.has(session) || ownedSessions.has(binding.sessionId)) throw invalid(new Error('duplicate_computer_session'));
      sessions.add(session); ownedSessions.add(binding.sessionId); objects.set(driver, ownedSessions);
      // The factory produces metadata and deferred callbacks only. No ComputerUse/driver operation runs here.
      const tools = createComputerTools(binding, () => { throw new Error('host_computer_metadata_only'); });
      for (const tool of tools) {
        const definition = tool.definition;
        if (definition.provider === 'core' || definition.id.startsWith('core.')) throw invalid();
        const identity = JSON.stringify([definition.id, definition.version]);
        if (identities.has(identity)) throw invalid(new Error('duplicate_computer_tool'));
        identities.add(identity); definitions.push(frozen(structuredClone(definition)));
      }
      // Keep only the declared binding contract; never retain injected endpoint/module/script properties.
      bindings.push(Object.freeze({ ...metadata, limits: binding.limits, labels: binding.labels, driver: binding.driver }));
    }
    return Object.freeze({ bindings: Object.freeze(bindings), definitions: Object.freeze(definitions) });
  } catch (error) {
    if (error instanceof Error && error.message === 'agent_computer_registration_invalid') throw error;
    throw invalid(error);
  }
}
