k9s:
  liveViewAutoRefresh: true
  refreshRate: 2
  apiServerTimeout: 15s
  maxConnRetry: 5
  readOnly: true
  defaultView: pods
  portForwardAddress: localhost
  ui:
    enableMouse: true
    headless: false
    logoless: false
    crumbsless: false
    reactive: true
    noIcons: false
  logger:
    tail: 200
    buffer: 5000
    sinceSeconds: 1800
    fullScreen: false
    textWrap: true
    showTime: true
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
