"""P2 — platform 네임스페이스 state DDL (진짜 횡단 5테이블. **참조용 — register_schema 로 배선 금지**).

⚠ platform 은 **코어 소유**다. P1 orchestrator 의 register_schema 는 ns∈{core,platform} 을 거부한다
(보안 경계). 따라서 이 DDL 은 **코어가** 부트스트랩에서 provision 한다(코어 세션 ASK:
secu-agent/docs/design/p2-platform-provision-CORE-ASK.md). 이 모듈은 그 SSOT 사본·검증용일 뿐 배선 대상이 아니다.

P2 재귀속(2026-07-12): 원 자동추출 8테이블 중 scan/screenshot/asset_owner 는 SMB 전용이라 skill_smb 로 이동.
platform 잔여 = 진짜 횡단 5개: control_flag, pipeline_heartbeat, pipeline_run, service_reply_message, devops_target.
"""

NAMESPACE = 'platform'

# P2 재귀속(2026-07-12): scan/screenshot/asset_owner 는 SMB 전용이라 skill_smb 로 이동. platform 은 진짜 횡단 5개만.
TABLES = ['control_flag', 'pipeline_heartbeat', 'pipeline_run', 'service_reply_message', 'devops_target']

IDLESS_TABLES = ['control_flag', 'pipeline_heartbeat']

BASELINE_DDL = """\
CREATE TABLE IF NOT EXISTS devops_target (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL,
    service TEXT NOT NULL,
    source TEXT NOT NULL,
    day_bucket TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    access_count BIGINT DEFAULT 0,
    discovered_at DOUBLE PRECISION NOT NULL,
    last_seen_at DOUBLE PRECISION NOT NULL,
    last_task_at DOUBLE PRECISION,
    finding_count BIGINT DEFAULT 0,
    last_reason TEXT,
    retry_after DOUBLE PRECISION,
    claimed_by BIGINT,
    claimed_at DOUBLE PRECISION,
    cycle_key TEXT,
    cycle_scanned_at DOUBLE PRECISION,
    cycle_finding_count BIGINT NOT NULL DEFAULT 0,
    UNIQUE(url, day_bucket)
);
CREATE INDEX IF NOT EXISTS idx_devops_target_status
    ON devops_target(status, day_bucket, access_count DESC);

CREATE TABLE IF NOT EXISTS service_reply_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain TEXT NOT NULL,
    thread_id BIGINT,
    direction TEXT NOT NULL,
    message_id TEXT,
    in_reply_to TEXT,
    references_header TEXT,
    root_message_id TEXT,
    subject TEXT,
    subject_tag TEXT,
    mail_from TEXT,
    mail_to TEXT,
    mail_cc TEXT,
    body_excerpt TEXT,
    body_html TEXT,
    agent_verdict TEXT NOT NULL DEFAULT 'pending',
    decision_reason TEXT,
    extracted_owner_json TEXT NOT NULL DEFAULT '{}',
    received_at DOUBLE PRECISION NOT NULL,
    UNIQUE (message_id)
);
CREATE INDEX IF NOT EXISTS idx_service_reply_message_thread
    ON service_reply_message(domain, thread_id);
CREATE INDEX IF NOT EXISTS idx_service_reply_message_verdict
    ON service_reply_message(domain, agent_verdict, direction);
CREATE INDEX IF NOT EXISTS idx_service_reply_message_subject_tag
    ON service_reply_message(domain, subject_tag);

CREATE TABLE IF NOT EXISTS control_flag (
    component TEXT PRIMARY KEY,
    enabled BIGINT NOT NULL DEFAULT 1,
    run_now BIGINT NOT NULL DEFAULT 0,
    interval_seconds DOUBLE PRECISION,
    updated_by TEXT,
    updated_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS pipeline_heartbeat (
    component TEXT PRIMARY KEY,
    phase TEXT,
    detail TEXT,
    pid BIGINT,
    last_beat DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS pipeline_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component TEXT NOT NULL,
    started_at DOUBLE PRECISION NOT NULL,
    finished_at DOUBLE PRECISION,
    status TEXT NOT NULL DEFAULT 'running',
    subnets_swept BIGINT NOT NULL DEFAULT 0,
    hosts_found BIGINT NOT NULL DEFAULT 0,
    shares_found BIGINT NOT NULL DEFAULT 0,
    shares_walked BIGINT NOT NULL DEFAULT 0,
    owners_enriched BIGINT NOT NULL DEFAULT 0,
    detail TEXT
);
CREATE INDEX IF NOT EXISTS idx_pipeline_run_started
    ON pipeline_run(component, started_at DESC);
"""

# (note, ddl) 순서 고정
MIGRATIONS = [
    ('devops_target: DevOps/SSO URL target weekly cycle progress (Confluence SSO mirror). baseline CREATE 에 이미 cycle_key 포함 — 구 DB용 멱등 마이그레이션.', 'ALTER TABLE devops_target ADD COLUMN IF NOT EXISTS cycle_key TEXT'),
    ('devops_target: baseline 에 이미 존재 — 멱등.', 'ALTER TABLE devops_target ADD COLUMN IF NOT EXISTS cycle_scanned_at DOUBLE PRECISION'),
    ('devops_target: baseline 에 이미 존재 — 멱등.', 'ALTER TABLE devops_target ADD COLUMN IF NOT EXISTS cycle_finding_count BIGINT NOT NULL DEFAULT 0'),
    ('devops_target: baseline 에 이미 존재 — 멱등.', 'ALTER TABLE devops_target ADD COLUMN IF NOT EXISTS retry_after DOUBLE PRECISION'),
    ('devops_target 추가 인덱스 (_ensure_domain_schema 내).', 'CREATE INDEX IF NOT EXISTS idx_devops_target_cycle ON devops_target(service, cycle_key, cycle_scanned_at)'),
    ('devops_target 추가 인덱스 (_ensure_domain_schema 내).', 'CREATE INDEX IF NOT EXISTS idx_devops_target_retry ON devops_target(service, status, retry_after)'),
    ('service_reply_message: baseline CREATE 에 이미 decision_reason 포함 — 구 DB용 멱등 마이그레이션.', 'ALTER TABLE service_reply_message ADD COLUMN IF NOT EXISTS decision_reason TEXT'),
    ('service_reply_message: baseline 에 이미 존재 — 멱등.', "ALTER TABLE service_reply_message ADD COLUMN IF NOT EXISTS extracted_owner_json TEXT NOT NULL DEFAULT '{}'"),
]

BACKFILLS = """\

"""

NOTES = """\
P2 재귀속(2026-07-12): 원 자동추출 8 → **진짜 횡단 5테이블**(control_flag, pipeline_heartbeat, pipeline_run, service_reply_message, devops_target). scan/screenshot/asset_owner 는 SMB 전용이라 skill_smb 로 이동. **platform 은 코어 소유** — register_schema 로 배선하지 말 것(orchestrator 거부). 이 모듈은 SSOT 사본·검증용.

이 네임스페이스에 대한 백필 UPDATE 는 없음(_ensure_domain_schema 백필은 report_thread/mail/dev_web 대상, platform 5개 중 어느 것도 UPDATE 안 함).

ALTER 없는 테이블: control_flag, pipeline_heartbeat, pipeline_run — baseline DDL 이 전부.

★ devops_target(4)·service_reply_message(2)의 ADD COLUMN IF NOT EXISTS 6개는 **구 DB에는 no-op이 아니다**(codex C): relocate된 구 shape는 컬럼이 없을 수 있고 CREATE IF NOT EXISTS는 누락 컬럼을 안 채운다 → 인덱스 실패. **코어 provision 시 idempotent migration으로 반드시 보존**(브리프 정정 참조). fresh DB에서만 no-op.

idless: control_flag·pipeline_heartbeat 2개(component PK, id 없음) — **코어가 등록**(register_idless_table). asset_owner 는 skill_smb 로 이동해 그쪽 idless. 나머지 platform(pipeline_run/service_reply_message/devops_target)은 id BIGINT IDENTITY PK 보유.

cross-namespace 참조(FK 없음, opaque id): pipeline_run/pipeline_heartbeat/control_flag 는 SMB·dev_web·github·confluence 파이프라인이 component 문자열로 공유(codex C 확인: pipeline_run도 4도메인 논리 writer). service_reply_message 는 domain 컬럼으로 여러 도메인 답장 공유 저장. devops_target 은 github·confluence 공용 SSO 미러 타깃(url,day_bucket UNIQUE, 외부 FK 없음).

순서 의존: 없음(모든 CREATE TABLE IF NOT EXISTS 는 상호 FK 없어 순서 무관). 단 _ensure_domain_schema 는 _DOMAIN_SCHEMA 전체 실행 후 ALTER 를 돌리므로, baseline → migrations 순서만 지키면 됨.

public 참조: 없음. state_domain 모듈은 secu_agent.state(코어) connect 풀만 재사용하며 platform 테이블은 코어 public 스키마 테이블을 참조하지 않음.
"""
