"""P2 추출 — skill_dev_web 네임스페이스 state DDL (자동생성. W2-a: plugin/bootstrap 이 register_schema 로 배선됨(dormant·미적용)).
state_domain.py 에서 이 네임스페이스 테이블의 baseline/migrations/backfill을 verbatim 추출.
컷오버(P1 후): register_schema("skill_dev_web", BASELINE_DDL, migrations=MIGRATIONS, idless_tables=IDLESS).
DDL-as-data — 포트 시그니처 무관. 원본 대조 검증 필요.
tables: web_target_domain, dev_web_target, dev_web_report_thread, dev_web_recheck_result
"""

NAMESPACE = 'skill_dev_web'

TABLES = ['web_target_domain', 'dev_web_target', 'dev_web_report_thread', 'dev_web_recheck_result']

IDLESS_TABLES = []

BASELINE_DDL = """\
CREATE TABLE IF NOT EXISTS web_target_domain (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain TEXT NOT NULL,
    source TEXT NOT NULL,
    day_bucket TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    event_count BIGINT DEFAULT 0,
    discovered_at DOUBLE PRECISION NOT NULL,
    last_seen_at DOUBLE PRECISION NOT NULL,
    last_task_at DOUBLE PRECISION,
    finding_count BIGINT DEFAULT 0,
    last_reason TEXT,
    claimed_by BIGINT,
    claimed_at DOUBLE PRECISION,
    UNIQUE(domain, day_bucket)
);
CREATE INDEX IF NOT EXISTS idx_web_target_status
    ON web_target_domain(status, day_bucket, event_count DESC);
CREATE TABLE IF NOT EXISTS dev_web_target (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL,
    domain TEXT NOT NULL,
    source TEXT NOT NULL,
    day_bucket TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    event_count BIGINT DEFAULT 0,
    priority_score BIGINT NOT NULL DEFAULT 0,
    discovered_at DOUBLE PRECISION NOT NULL,
    last_seen_at DOUBLE PRECISION NOT NULL,
    last_task_at DOUBLE PRECISION,
    finding_count BIGINT DEFAULT 0,
    report_thread_id BIGINT,
    last_reason TEXT,
    evidence_ref TEXT,
    retry_after DOUBLE PRECISION,
    claimed_by BIGINT,
    claimed_at DOUBLE PRECISION,
    cycle_key TEXT,
    UNIQUE(url, day_bucket)
);
CREATE INDEX IF NOT EXISTS idx_dev_web_target_status
    ON dev_web_target(status, day_bucket, event_count DESC);
CREATE INDEX IF NOT EXISTS idx_dev_web_target_domain
    ON dev_web_target(domain, day_bucket);
CREATE TABLE IF NOT EXISTS dev_web_report_thread (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id BIGINT,
    finding_id BIGINT,
    domain TEXT NOT NULL,
    url TEXT NOT NULL,
    subject_tag TEXT NOT NULL,
    severity TEXT,
    status TEXT NOT NULL DEFAULT 'draft',
    recipient TEXT,
    report_json TEXT NOT NULL DEFAULT '{}',
    request_message_id TEXT,
    attempt_count BIGINT NOT NULL DEFAULT 0,
    last_reason TEXT,
    retry_after DOUBLE PRECISION,
    claimed_by BIGINT,
    claimed_at DOUBLE PRECISION,
    first_reported_at DOUBLE PRECISION,
    first_cycle_key TEXT,
    last_cycle_key TEXT,
    cycle_keys TEXT NOT NULL DEFAULT '[]',
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_dev_web_report_thread_status
    ON dev_web_report_thread(status, claimed_at);
CREATE INDEX IF NOT EXISTS idx_dev_web_report_thread_domain
    ON dev_web_report_thread(domain, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_dev_web_report_thread_finding
    ON dev_web_report_thread(finding_id);
CREATE TABLE IF NOT EXISTS dev_web_recheck_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    target_id BIGINT,
    finding_id BIGINT,
    domain TEXT NOT NULL,
    url TEXT NOT NULL,
    verdict TEXT NOT NULL,
    verification_json TEXT NOT NULL DEFAULT '{}',
    evidence_ref TEXT,
    error TEXT,
    created_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_dev_web_recheck_result_thread
    ON dev_web_recheck_result(thread_id, created_at DESC);
"""

# (note, ddl) 순서 고정
MIGRATIONS = [
    ('web_target_domain (state_domain.py:660-662)', 'ALTER TABLE web_target_domain ADD COLUMN IF NOT EXISTS claimed_by BIGINT'),
    ('web_target_domain (state_domain.py:663-666)', 'ALTER TABLE web_target_domain ADD COLUMN IF NOT EXISTS claimed_at DOUBLE PRECISION'),
    ('dev_web E2E target retry window (state_domain.py:854-857)', 'ALTER TABLE dev_web_target ADD COLUMN IF NOT EXISTS retry_after DOUBLE PRECISION'),
    ('state_domain.py:858-861', 'ALTER TABLE dev_web_target ADD COLUMN IF NOT EXISTS priority_score BIGINT NOT NULL DEFAULT 0'),
    ('state_domain.py:862-865', 'ALTER TABLE dev_web_target ADD COLUMN IF NOT EXISTS cycle_key TEXT'),
    ('state_domain.py:866-869', 'CREATE INDEX IF NOT EXISTS idx_dev_web_target_retry ON dev_web_target(status, retry_after)'),
    ('state_domain.py:870-873', 'CREATE INDEX IF NOT EXISTS idx_dev_web_target_priority ON dev_web_target(status, day_bucket, priority_score DESC, event_count DESC)'),
    ('state_domain.py:874-877', 'CREATE INDEX IF NOT EXISTS idx_dev_web_target_cycle ON dev_web_target(cycle_key, status, priority_score DESC, event_count DESC)'),
    ('state_domain.py:878-881', 'ALTER TABLE dev_web_report_thread ADD COLUMN IF NOT EXISTS retry_after DOUBLE PRECISION'),
    ('state_domain.py:882-885', 'ALTER TABLE dev_web_report_thread ADD COLUMN IF NOT EXISTS first_cycle_key TEXT'),
    ('state_domain.py:886-889', 'ALTER TABLE dev_web_report_thread ADD COLUMN IF NOT EXISTS last_cycle_key TEXT'),
    ('state_domain.py:890-893', "ALTER TABLE dev_web_report_thread ADD COLUMN IF NOT EXISTS cycle_keys TEXT NOT NULL DEFAULT '[]'"),
    ('state_domain.py:894-897', 'CREATE INDEX IF NOT EXISTS idx_dev_web_report_thread_retry ON dev_web_report_thread(status, retry_after)'),
    ('state_domain.py:898-901', 'CREATE INDEX IF NOT EXISTS idx_dev_web_report_thread_cycle ON dev_web_report_thread(last_cycle_key, status, updated_at DESC)'),
]

BACKFILLS = """\
-- state_domain.py:1080-1097, _backfill_dev_web_cycles(c), called at line 1059 inside _ensure_domain_schema. _LEGACY_REPORT_CYCLE_KEY = "2026-W25" (line 44); cycle_keys param = json.dumps([_LEGACY_REPORT_CYCLE_KEY]); current = smb_current_cycle_key().
UPDATE dev_web_report_thread SET first_cycle_key=?, last_cycle_key=?, cycle_keys=CASE WHEN cycle_keys IS NULL OR TRIM(cycle_keys)='' OR TRIM(cycle_keys)='[]' THEN ? ELSE cycle_keys END WHERE (first_cycle_key IS NULL OR TRIM(first_cycle_key)='') AND (last_cycle_key IS NULL OR TRIM(last_cycle_key)='');
-- params: (_LEGACY_REPORT_CYCLE_KEY, _LEGACY_REPORT_CYCLE_KEY, cycle_keys)

UPDATE dev_web_target SET cycle_key=? WHERE cycle_key IS NULL OR TRIM(cycle_key)='';
-- params: (current,) where current = smb_current_cycle_key()
"""

NOTES = """\
Cross-namespace 참조/의존 주의: (1) dev_web_target.report_thread_id, dev_web_report_thread.target_id/finding_id, dev_web_recheck_result.thread_id/target_id/finding_id 는 FK 제약이 아닌 순수 BIGINT 컬럼이라 DDL상 다른 테이블 의존 없음(스키마 분리 시 안전). (2) 백필 _backfill_dev_web_cycles 는 smb_current_cycle_key() (SMB 네임스페이스 함수)와 모듈 상수 _LEGACY_REPORT_CYCLE_KEY, json.dumps 에 의존 — 코드 이전 시 이 헬퍼/상수를 함께 가져와야 함. (3) 실행 순서 의존: baseline(_DOMAIN_SCHEMA) 전체 실행 후 ALTER 블록, 그 뒤 백필 순으로 실행됨(_ensure_domain_schema, 656-1059행). ALTER는 IF NOT EXISTS 멱등, 백필은 조건부라 재실행 안전. (4) idless 없음: register_idless_table 는 asset_owner/control_flag/pipeline_heartbeat 만 등록, 이 네임스페이스 4개 테이블은 모두 IDENTITY PK 보유. (5) web_target_domain 은 지시대로 dev_web 에 흡수했으나, dev_web_target 과 컬럼 구조가 유사할 뿐 별개 테이블임(migration으로 통합 여부는 스키마 소유자 결정 필요). (6) dev_web 관련 ALTER/INDEX 중 다른 도메인(smb_share, smb_target_subnet, github_repo_target, confluence_space_target, devops_target, github_report_thread) 블록은 제외함.
"""
