"""P2 추출 — skill_confluence 네임스페이스 state DDL (자동생성. W2-a: plugin/bootstrap 이 register_schema 로 배선됨(dormant·미적용)).
state_domain.py 에서 이 네임스페이스 테이블의 baseline/migrations/backfill을 verbatim 추출.
컷오버(P1 후): register_schema("skill_confluence", BASELINE_DDL, migrations=MIGRATIONS, idless_tables=IDLESS).
DDL-as-data — 포트 시그니처 무관. 원본 대조 검증 필요.
tables: confluence_space_target, confluence_report_thread, confluence_recheck_result
"""

NAMESPACE = 'skill_confluence'

TABLES = ['confluence_space_target', 'confluence_report_thread', 'confluence_recheck_result']

IDLESS_TABLES = []

BASELINE_DDL = """\
CREATE TABLE IF NOT EXISTS confluence_space_target (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_key TEXT NOT NULL UNIQUE,
    space_name TEXT,
    space_type TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    claimed_by BIGINT,
    claimed_at DOUBLE PRECISION,
    last_scanned_at DOUBLE PRECISION,
    finding_count BIGINT DEFAULT 0,
    last_reason TEXT,
    retry_after DOUBLE PRECISION,
    first_seen DOUBLE PRECISION NOT NULL,
    last_seen DOUBLE PRECISION NOT NULL,
    cycle_key TEXT,
    cycle_scanned_at DOUBLE PRECISION,
    cycle_finding_count BIGINT NOT NULL DEFAULT 0,
    extra_json TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_confluence_space_target_roll
    ON confluence_space_target(status, last_scanned_at);
CREATE TABLE IF NOT EXISTS confluence_report_thread (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_key TEXT NOT NULL,
    finding_id BIGINT NOT NULL,
    finding_ids TEXT NOT NULL DEFAULT '[]',
    subject_tag TEXT NOT NULL,
    severity TEXT,
    status TEXT NOT NULL DEFAULT 'reported',
    recipient TEXT,
    owner_recipient TEXT,
    report_json TEXT NOT NULL DEFAULT '{}',
    report_html TEXT,
    notified_at DOUBLE PRECISION,
    attempt_count BIGINT NOT NULL DEFAULT 0,
    last_reason TEXT,
    retry_after DOUBLE PRECISION,
    claimed_by BIGINT,
    claimed_at DOUBLE PRECISION,
    first_reported_at DOUBLE PRECISION,
    first_cycle_key TEXT,
    last_cycle_key TEXT,
    cycle_keys TEXT NOT NULL DEFAULT '[]',
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_confluence_report_thread_status
    ON confluence_report_thread(status, claimed_at);
CREATE INDEX IF NOT EXISTS idx_confluence_report_thread_space
    ON confluence_report_thread(space_key, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_confluence_report_thread_finding
    ON confluence_report_thread(finding_id);
CREATE TABLE IF NOT EXISTS confluence_recheck_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    finding_id BIGINT,
    space_key TEXT NOT NULL,
    asset TEXT,
    verdict TEXT NOT NULL,
    verification_json TEXT NOT NULL DEFAULT '{}',
    error TEXT,
    created_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_confluence_recheck_result_thread
    ON confluence_recheck_result(thread_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_confluence_recheck_result_finding
    ON confluence_recheck_result(finding_id, created_at DESC);
"""

# (note, ddl) 순서 고정
MIGRATIONS = [
    ('confluence_space_target (state_domain.py:804-807)', 'ALTER TABLE confluence_space_target ADD COLUMN IF NOT EXISTS cycle_key TEXT'),
    ('state_domain.py:808-811', 'ALTER TABLE confluence_space_target ADD COLUMN IF NOT EXISTS cycle_scanned_at DOUBLE PRECISION'),
    ('state_domain.py:812-815', 'ALTER TABLE confluence_space_target ADD COLUMN IF NOT EXISTS cycle_finding_count BIGINT NOT NULL DEFAULT 0'),
    ('state_domain.py:816-819', 'ALTER TABLE confluence_space_target ADD COLUMN IF NOT EXISTS retry_after DOUBLE PRECISION'),
    ('state_domain.py:820-823', 'CREATE INDEX IF NOT EXISTS idx_confluence_space_target_cycle ON confluence_space_target(cycle_key, cycle_scanned_at)'),
    ('state_domain.py:824-827', 'CREATE INDEX IF NOT EXISTS idx_confluence_space_target_retry ON confluence_space_target(status, retry_after)'),
    ('confluence_report_thread (state_domain.py:948-951)', 'ALTER TABLE confluence_report_thread ADD COLUMN IF NOT EXISTS owner_recipient TEXT'),
    ('state_domain.py:952-955', "ALTER TABLE confluence_report_thread ADD COLUMN IF NOT EXISTS finding_ids TEXT NOT NULL DEFAULT '[]'"),
    ('state_domain.py:956-959', "ALTER TABLE confluence_report_thread ADD COLUMN IF NOT EXISTS report_json TEXT NOT NULL DEFAULT '{}'"),
    ('state_domain.py:960-963', 'ALTER TABLE confluence_report_thread ADD COLUMN IF NOT EXISTS report_html TEXT'),
    ('state_domain.py:964-967', 'ALTER TABLE confluence_report_thread ADD COLUMN IF NOT EXISTS notified_at DOUBLE PRECISION'),
    ('state_domain.py:968-971', 'ALTER TABLE confluence_report_thread ADD COLUMN IF NOT EXISTS retry_after DOUBLE PRECISION'),
    ('state_domain.py:972-975', 'ALTER TABLE confluence_report_thread ADD COLUMN IF NOT EXISTS first_reported_at DOUBLE PRECISION'),
    ('state_domain.py:976-979', 'ALTER TABLE confluence_report_thread ADD COLUMN IF NOT EXISTS first_cycle_key TEXT'),
    ('state_domain.py:980-983', 'ALTER TABLE confluence_report_thread ADD COLUMN IF NOT EXISTS last_cycle_key TEXT'),
    ('state_domain.py:984-987', "ALTER TABLE confluence_report_thread ADD COLUMN IF NOT EXISTS cycle_keys TEXT NOT NULL DEFAULT '[]'"),
    ('state_domain.py:988-991', 'CREATE INDEX IF NOT EXISTS idx_confluence_report_thread_retry ON confluence_report_thread(status, retry_after)'),
]

BACKFILLS = """\
-- _backfill_legacy_report_thread_cycles(c), state_domain.py:1065-1077.
-- _LEGACY_REPORT_CYCLE_KEY = "2026-W25" (line 44); cycle_keys = json.dumps([_LEGACY_REPORT_CYCLE_KEY]).
-- Loops for table in ("github_report_thread", "confluence_report_thread", "mail_thread"); the confluence_report_thread iteration:
UPDATE confluence_report_thread SET first_cycle_key=?, last_cycle_key=?, cycle_keys=CASE WHEN cycle_keys IS NULL OR TRIM(cycle_keys)='' OR TRIM(cycle_keys)='[]' THEN ? ELSE cycle_keys END WHERE (first_cycle_key IS NULL OR TRIM(first_cycle_key)='') AND (last_cycle_key IS NULL OR TRIM(last_cycle_key)='');
-- params: (_LEGACY_REPORT_CYCLE_KEY, _LEGACY_REPORT_CYCLE_KEY, cycle_keys)
"""

NOTES = """\
1) 백필은 confluence_report_thread에만 적용됨 (confluence_space_target, confluence_recheck_result는 백필 없음). 백필은 하드코딩된 여러 테이블 튜플 ("github_report_thread","confluence_report_thread","mail_thread")을 순회하는 공유 헬퍼 _backfill_legacy_report_thread_cycles 안에 있음 — confluence_report_thread만 verbatim으로 추출했으나, 분해 시 이 헬퍼가 3개 도메인(github/confluence/mail)을 걸쳐 있음에 주의. 2) _LEGACY_REPORT_CYCLE_KEY 상수(모듈 44행)에 의존하므로 백필을 옮길 때 이 상수도 함께 필요. 3) 이 3개 테이블 모두 id 컬럼 보유(GENERATED BY DEFAULT AS IDENTITY) → idless 미등록. register_idless_table 등록 대상은 asset_owner/control_flag/pipeline_heartbeat뿐(이 네임스페이스와 무관). 4) 마이그레이션 ALTER 블록은 인접한 github_repo_target/github_report_thread/devops/mail ALTER 사이에 끼어 있으나 confluence_* 대상만 추출함. 5) cross-namespace 참조: confluence_report_thread.finding_id / finding_ids, confluence_recheck_result.thread_id·finding_id는 FK 제약 없이 논리적 참조(thread_id→confluence_report_thread.id, finding_id→findings 도메인). 실제 FOREIGN KEY 선언은 DDL에 없음. 6) baseline CREATE TABLE에는 migrations의 ALTER로 추가되는 컬럼/인덱스가 이미 포함되어 있음(신규 DB는 CREATE로, 기존 DB는 ALTER로 멱등 수렴) — 순서 의존: baseline 먼저, 그 다음 migrations.
"""
