"""skill_quality 네임스페이스 — worker candidate 텔레메트리 이벤트 (#1 눈 read-model 원천).

v3.90 candidate ledger 침묵 게이트의 "판정은 부모/오케스트레이터에 위임" 설계를 받는 DB 영속층.
worker_result.json(파일)·FanoutReport(인메모리)에서 소멸하던 candidates_seen/accounted 를
이벤트 소싱으로 영속해, digisecu 게이트웨이(/gw/quality/candidates)가 read-only 로 소비한다.

설계 결정 (codex 적대 설계리뷰 반영):
- **이벤트표** (결과표 아님): started(부모 spawn 전) / worker_result(워커 기록 직후) /
  parent_observed(부모 completion 분류 후) 3종. UNIQUE(attempt_id, event_kind) 로 자연 dedup —
  A(워커측)/B(부모측) 이중 기록이 서로 다른 event_kind 라 upsert 충돌 자체가 없다.
- **unknown ≠ 0**: candidates_seen/accounted 는 NULL 허용 — invalid/legacy/미계측을 0(측정된 깨끗함)과
  절대 합치지 않는다. result_valid=FALSE 인 parent_observed 가 "안 보임"을 명시적으로 남긴다.
- **민감 컬럼 금지**: worker_label(host/repo/share 포함)·evidence_dir(경로) 는 컬럼으로 두지 않는다.
  게이트웨이는 base table 이 아니라 고정 컬럼 VIEW(worker_candidate_quality)만 GRANT 받는다.
- **3축 식별**: domain(게이트웨이 귀속 축, smb|dev_web|github|confluence 고정 어휘) /
  worker_type(spec task_type 원문 — smb_task 등, 도메인명과 혼동 금지) / component(platform.pipeline_run
  component 축 재사용 — 게이트웨이 runtime_components 분류와 호환).
- 신규 네임스페이스라 레거시 public 잔재 없음 — 처음부터 connection("skill_quality") 로만 접근.
  DDL 적용은 명시적 apply_schema("skill_quality") (lazy first-worker DDL 금지 — codex 배포 지적).

tables: worker_candidate_event (+VIEW worker_candidate_quality)
"""

NAMESPACE = 'skill_quality'

TABLES = ['worker_candidate_event']

IDLESS_TABLES = []

BASELINE_DDL = """\
CREATE TABLE IF NOT EXISTS worker_candidate_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id TEXT NOT NULL,
    event_kind TEXT NOT NULL,
    domain TEXT NOT NULL,
    worker_type TEXT NOT NULL,
    component TEXT NOT NULL,
    result_valid BOOLEAN,
    execution_status TEXT,
    reason_code TEXT,
    ledger_enforced BOOLEAN,
    metrics_version BIGINT,
    candidates_seen BIGINT,
    candidates_accounted BIGINT,
    worker_reported_findings_count BIGINT,
    recorded_at DOUBLE PRECISION NOT NULL,
    UNIQUE(attempt_id, event_kind)
);
CREATE INDEX IF NOT EXISTS idx_worker_candidate_event_domain
    ON worker_candidate_event(domain, recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_worker_candidate_event_silent
    ON worker_candidate_event(domain, recorded_at DESC)
    WHERE candidates_seen > 0 AND candidates_accounted = 0;
CREATE OR REPLACE VIEW worker_candidate_quality AS
    SELECT attempt_id, event_kind, domain, worker_type, component,
           result_valid, execution_status, reason_code, ledger_enforced,
           metrics_version, candidates_seen, candidates_accounted,
           worker_reported_findings_count, recorded_at
    FROM worker_candidate_event;
"""

# (note, ddl) 순서 고정 — append-only
MIGRATIONS = []

BACKFILLS = ""

NOTES = """\
1) 컬럼 시맨틱: event_kind=started 는 식별 3축+recorded_at 만 의미(나머지 NULL).
   event_kind=worker_result 는 워커 자기 기록 — result_valid=TRUE 고정, ledger_enforced/
   metrics_version/candidates_*/reason_code 를 워커 로컬 진실로 채움.
   event_kind=parent_observed 는 부모(어댑터/자체 루프)의 관측 — result_valid 가 워커 결과 파싱
   성공 여부이고 FALSE 면 candidates_*=NULL(unknown) 이 계약.
2) worker_reported_findings_count 명명 의도: 워커 자기보고 값이며 도메인별 한계가 있다
   (smb_task_worker 는 실제 제출 수가 아니라 saw_terminal 0/1). 집계 시 합산 금지, 존재 신호로만.
3) candidates_seen 단위는 도구별 이질(hit/페이지/finding — candidate_counters.py) — 비율/차감
   계산 금지, 침묵 판정은 이진(seen>0 AND accounted=0)만 유효.
4) recorded_at 은 기존 규약대로 Python time.time() epoch (DOUBLE PRECISION) — DB server default
   미사용(코어 스키마 오케스트레이터 checksum 결정성 및 타 테이블 관례 일치).
5) VIEW 는 기밀성 경계: 게이트웨이 RO 롤에는 worker_candidate_quality 만 GRANT (base table 금지 —
   digisecu-employee gateway/sql/003 참조). 컬럼 추가 시 VIEW 는 명시적으로만 확장.
6) P2 컷오버 무관 신규 네임스페이스 — 모놀리식 state_domain.py 에 baseline 없음(이 모듈이 유일 소스).
"""
