"""P2 추출 — skill_github 네임스페이스 state DDL (자동생성. W2-a: plugin/bootstrap 이 register_schema 로 배선됨(dormant·미적용)).
state_domain.py 에서 이 네임스페이스 테이블의 baseline/migrations/backfill을 verbatim 추출.
컷오버(P1 후): register_schema("skill_github", BASELINE_DDL, migrations=MIGRATIONS, idless_tables=IDLESS).
DDL-as-data — 포트 시그니처 무관. 원본 대조 검증 필요.
tables: github_repo_target, github_report_thread, github_recheck_result
"""

NAMESPACE = 'skill_github'

TABLES = ['github_repo_target', 'github_report_thread', 'github_recheck_result']

IDLESS_TABLES = []

BASELINE_DDL = """\
CREATE TABLE IF NOT EXISTS github_repo_target (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo TEXT NOT NULL UNIQUE,
    default_branch TEXT,
    pushed_at TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    claimed_by BIGINT,
    claimed_at DOUBLE PRECISION,
    last_scanned_at DOUBLE PRECISION,
    last_scanned_sha TEXT,
    finding_count BIGINT DEFAULT 0,
    last_reason TEXT,
    retry_after DOUBLE PRECISION,
    first_seen DOUBLE PRECISION NOT NULL,
    last_seen DOUBLE PRECISION NOT NULL,
    cycle_key TEXT,
    cycle_scanned_at DOUBLE PRECISION,
    cycle_finding_count BIGINT NOT NULL DEFAULT 0,
    extra_json TEXT NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_github_repo_target_roll
    ON github_repo_target(status, last_scanned_at);

CREATE TABLE IF NOT EXISTS github_report_thread (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo TEXT NOT NULL,
    finding_id BIGINT NOT NULL,
    finding_ids TEXT NOT NULL DEFAULT '[]',
    subject_tag TEXT NOT NULL,
    severity TEXT,
    status TEXT NOT NULL DEFAULT 'reported',
    recipient TEXT,
    owner_recipient TEXT,
    report_json TEXT NOT NULL DEFAULT '{}',
    report_html TEXT,
    notified_at DOUBLE PRECISION,
    attempt_count BIGINT NOT NULL DEFAULT 0,
    last_reason TEXT,
    retry_after DOUBLE PRECISION,
    claimed_by BIGINT,
    claimed_at DOUBLE PRECISION,
    first_reported_at DOUBLE PRECISION,
    first_cycle_key TEXT,
    last_cycle_key TEXT,
    cycle_keys TEXT NOT NULL DEFAULT '[]',
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_github_report_thread_status
    ON github_report_thread(status, claimed_at);
CREATE INDEX IF NOT EXISTS idx_github_report_thread_repo
    ON github_report_thread(repo, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_github_report_thread_finding
    ON github_report_thread(finding_id);

CREATE TABLE IF NOT EXISTS github_recheck_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    finding_id BIGINT,
    repo TEXT NOT NULL,
    path TEXT,
    verdict TEXT NOT NULL,
    verification_json TEXT NOT NULL DEFAULT '{}',
    error TEXT,
    created_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_github_recheck_result_thread
    ON github_recheck_result(thread_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_github_recheck_result_finding
    ON github_recheck_result(finding_id, created_at DESC);
"""

# (note, ddl) 순서 고정
MIGRATIONS = [
    ('v3.78 G1: github_repo_target commit dedup 커서 (line 774-777)', 'ALTER TABLE github_repo_target ADD COLUMN IF NOT EXISTS last_scanned_sha TEXT'),
    ('GitHub target weekly cycle progress (line 779-782)', 'ALTER TABLE github_repo_target ADD COLUMN IF NOT EXISTS cycle_key TEXT'),
    ('line 783-786', 'ALTER TABLE github_repo_target ADD COLUMN IF NOT EXISTS cycle_scanned_at DOUBLE PRECISION'),
    ('line 787-790', 'ALTER TABLE github_repo_target ADD COLUMN IF NOT EXISTS cycle_finding_count BIGINT NOT NULL DEFAULT 0'),
    ('line 791-794', 'ALTER TABLE github_repo_target ADD COLUMN IF NOT EXISTS retry_after DOUBLE PRECISION'),
    ('line 795-798', 'CREATE INDEX IF NOT EXISTS idx_github_repo_target_cycle ON github_repo_target(cycle_key, cycle_scanned_at)'),
    ('line 799-802', 'CREATE INDEX IF NOT EXISTS idx_github_repo_target_retry ON github_repo_target(status, retry_after)'),
    ('GitHub E2E report/recheck thread columns idempotent (line 903-906)', 'ALTER TABLE github_report_thread ADD COLUMN IF NOT EXISTS owner_recipient TEXT'),
    ('line 907-910', "ALTER TABLE github_report_thread ADD COLUMN IF NOT EXISTS finding_ids TEXT NOT NULL DEFAULT '[]'"),
    ('line 911-914', "ALTER TABLE github_report_thread ADD COLUMN IF NOT EXISTS report_json TEXT NOT NULL DEFAULT '{}'"),
    ('line 915-918', 'ALTER TABLE github_report_thread ADD COLUMN IF NOT EXISTS report_html TEXT'),
    ('line 919-922', 'ALTER TABLE github_report_thread ADD COLUMN IF NOT EXISTS notified_at DOUBLE PRECISION'),
    ('line 923-926', 'ALTER TABLE github_report_thread ADD COLUMN IF NOT EXISTS retry_after DOUBLE PRECISION'),
    ('line 927-930', 'ALTER TABLE github_report_thread ADD COLUMN IF NOT EXISTS first_reported_at DOUBLE PRECISION'),
    ('line 931-934', 'ALTER TABLE github_report_thread ADD COLUMN IF NOT EXISTS first_cycle_key TEXT'),
    ('line 935-938', 'ALTER TABLE github_report_thread ADD COLUMN IF NOT EXISTS last_cycle_key TEXT'),
    ('line 939-942', "ALTER TABLE github_report_thread ADD COLUMN IF NOT EXISTS cycle_keys TEXT NOT NULL DEFAULT '[]'"),
    ('line 943-946', 'CREATE INDEX IF NOT EXISTS idx_github_report_thread_retry ON github_report_thread(status, retry_after)'),
]

BACKFILLS = """\
-- _backfill_legacy_report_thread_cycles (line 1065-1077): loops over ("github_report_thread", "confluence_report_thread", "mail_thread"). github_report_thread 해당 UPDATE (table 명이 f-string 치환, params: (_LEGACY_REPORT_CYCLE_KEY, _LEGACY_REPORT_CYCLE_KEY, cycle_keys) where cycle_keys = json.dumps([_LEGACY_REPORT_CYCLE_KEY])):
UPDATE github_report_thread SET first_cycle_key=?, last_cycle_key=?, cycle_keys=CASE WHEN cycle_keys IS NULL OR TRIM(cycle_keys)='' OR TRIM(cycle_keys)='[]' THEN ? ELSE cycle_keys END WHERE (first_cycle_key IS NULL OR TRIM(first_cycle_key)='') AND (last_cycle_key IS NULL OR TRIM(last_cycle_key)='')
"""

NOTES = """\
idless: 세 테이블 모두 register_idless_table 미등록 — 각자 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY 보유. 등록된 idless는 asset_owner/control_flag/pipeline_heartbeat뿐(39-42행), skill_github 무관.

cross-namespace 주의:
1) 백필 _backfill_legacy_report_thread_cycles(1065-1077)는 하나의 f-string 루프로 github_report_thread + confluence_report_thread(skill_confluence) + mail_thread(다른 도메인)를 함께 UPDATE. 위 backfills에는 github_report_thread 부분만 verbatim 치환해 기재. 이 백필 함수는 _ensure_domain_schema 끝(1058행)에서 호출되며 _LEGACY_REPORT_CYCLE_KEY 상수·json.dumps 의존.
2) github_recheck_result는 migrations/backfill 전무 — baseline CREATE+INDEX 2개가 전체.
3) baseline DDL 원문 순서: github_repo_target(324-345) → github_report_thread(348-378) → github_recheck_result(381-395). v3.76 confluence_space_target가 github_repo_target 미러(397행 주석)이나 별 네임스페이스라 제외.
4) migrations는 _ensure_domain_schema의 대형 try 블록 안(다른 도메인 ALTER와 인터리브)에 있으며 실행 순서상 github_repo_target 블록(773-802)이 github_report_thread 블록(903-946)보다 먼저. 전체 블록은 except Exception: pass(1060행)로 감싸 권한 없는 ALTER 무시.
5) github_report_thread.finding_id BIGINT NOT NULL은 baseline 최초 정의(351행)이며 별도 ALTER 없음(단일 finding_id → finding_ids TEXT 확장은 migration으로 추가됨).
"""
