"""P2 추출 — skill_smb 네임스페이스 state DDL (자동생성. W2-a: plugin/bootstrap 이 register_schema 로 배선됨(dormant·미적용)).
state_domain.py 에서 이 네임스페이스 테이블의 baseline/migrations/backfill을 verbatim 추출.
컷오버(P1 후): register_schema("skill_smb", BASELINE_DDL, migrations=MIGRATIONS, idless_tables=IDLESS).
DDL-as-data — 포트 시그니처 무관. 원본 대조 검증 필요.
tables: smb_credential, smb_share, smb_directory, smb_file, smb_file_hit, smb_target_subnet, mail_thread, mail_message, mail_reply_decision, mail_reverify_result
"""

NAMESPACE = 'skill_smb'

TABLES = ['smb_credential', 'smb_share', 'smb_directory', 'smb_file', 'smb_file_hit', 'smb_target_subnet', 'mail_thread', 'mail_message', 'mail_reply_decision', 'mail_reverify_result', 'scan', 'asset_owner', 'screenshot']

# asset_owner 는 ip PK(=id 컬럼 없음) → INSERT RETURNING 자동부착 제외 대상. (P2 재귀속: platform→skill_smb)
IDLESS_TABLES = ['asset_owner']

BASELINE_DDL = """\
CREATE TABLE IF NOT EXISTS smb_credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    username TEXT NOT NULL,
    password_ref TEXT NOT NULL,
    enabled BIGINT NOT NULL DEFAULT 1,
    last_used DOUBLE PRECISION,
    created_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS smb_share (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fingerprint TEXT UNIQUE NOT NULL,
    subnet TEXT NOT NULL,
    host TEXT NOT NULL,
    share TEXT NOT NULL,
    first_seen DOUBLE PRECISION NOT NULL,
    last_seen DOUBLE PRECISION NOT NULL,
    last_scan_id BIGINT,
    status TEXT NOT NULL DEFAULT 'pending',
    null_login_ok BIGINT,
    guest_login_ok BIGINT,
    auth_login_ok BIGINT,
    auth_credential_id BIGINT,
    share_read BIGINT NOT NULL DEFAULT 0,
    share_write BIGINT NOT NULL DEFAULT 0,
    access_modes TEXT,
    walk_done_at DOUBLE PRECISION,
    walk_file_count BIGINT NOT NULL DEFAULT 0,
    severity TEXT,
    summary TEXT,
    hits_count BIGINT NOT NULL DEFAULT 0,
    processed_at DOUBLE PRECISION,
    evidence_dir TEXT,
    retry_count BIGINT NOT NULL DEFAULT 0,
    retry_after DOUBLE PRECISION,
    last_error_kind TEXT,
    last_error TEXT,
    listing_review TEXT,
    listing_review_at DOUBLE PRECISION,
    claimed_by BIGINT,
    claimed_at DOUBLE PRECISION,
    excluded_reason TEXT,
    excluded_at DOUBLE PRECISION,
    exception_reason TEXT,
    exception_thread_id BIGINT,
    exception_approved_by TEXT,
    exception_at DOUBLE PRECISION,
    cycle_key TEXT,
    cycle_seen_at DOUBLE PRECISION,
    cycle_walk_done_at DOUBLE PRECISION,
    FOREIGN KEY (auth_credential_id) REFERENCES smb_credential(id)
);
CREATE INDEX IF NOT EXISTS idx_smb_share_status ON smb_share(status);
CREATE INDEX IF NOT EXISTS idx_smb_share_last_seen ON smb_share(last_seen);

CREATE TABLE IF NOT EXISTS smb_directory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_id BIGINT NOT NULL,
    path TEXT NOT NULL,
    depth BIGINT NOT NULL DEFAULT 0,
    listable BIGINT,
    readable BIGINT,
    writable BIGINT,
    error TEXT,
    last_seen DOUBLE PRECISION NOT NULL,
    FOREIGN KEY (share_id) REFERENCES smb_share(id),
    UNIQUE (share_id, path)
);
CREATE INDEX IF NOT EXISTS idx_smb_directory_share ON smb_directory(share_id);
CREATE INDEX IF NOT EXISTS idx_smb_directory_access ON smb_directory(listable, writable);

CREATE TABLE IF NOT EXISTS smb_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_id BIGINT NOT NULL,
    path TEXT NOT NULL,
    size BIGINT NOT NULL DEFAULT 0,
    is_text_candidate BIGINT NOT NULL DEFAULT 0,
    suspicious_name BIGINT NOT NULL DEFAULT 0,
    file_read BIGINT,
    file_write BIGINT,
    fetch_status TEXT,
    scan_status TEXT,
    hits_count BIGINT NOT NULL DEFAULT 0,
    last_walked_at DOUBLE PRECISION NOT NULL,
    last_fetched_at DOUBLE PRECISION,
    last_scanned_at DOUBLE PRECISION,
    agent_note TEXT,
    agent_tags TEXT,
    review_severity TEXT,
    review_summary TEXT,
    review_status TEXT,
    reviewed_at DOUBLE PRECISION,
    FOREIGN KEY (share_id) REFERENCES smb_share(id),
    UNIQUE (share_id, path)
);
CREATE INDEX IF NOT EXISTS idx_smb_file_share ON smb_file(share_id);
CREATE INDEX IF NOT EXISTS idx_smb_file_scan ON smb_file(scan_status);

CREATE TABLE IF NOT EXISTS smb_file_hit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT NOT NULL,
    category TEXT NOT NULL,
    kind TEXT NOT NULL,
    masked TEXT NOT NULL,
    line_no BIGINT NOT NULL,
    line_preview TEXT NOT NULL,
    agent_verdict TEXT NOT NULL DEFAULT 'pending',
    agent_confidence DOUBLE PRECISION,
    agent_note TEXT,
    validation_json TEXT,
    triaged_at DOUBLE PRECISION,
    FOREIGN KEY (file_id) REFERENCES smb_file(id)
);
CREATE INDEX IF NOT EXISTS idx_smb_file_hit_file ON smb_file_hit(file_id);
CREATE INDEX IF NOT EXISTS idx_smb_file_hit_verdict ON smb_file_hit(agent_verdict);

CREATE TABLE IF NOT EXISTS smb_target_subnet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subnet TEXT NOT NULL,
    note TEXT,
    charter_ref TEXT,
    enabled BIGINT NOT NULL DEFAULT 1,
    added_by TEXT,
    claimed_by BIGINT,
    claimed_at DOUBLE PRECISION,
    cycle_key TEXT,
    cycle_swept_at DOUBLE PRECISION,
    cycle_hosts_found BIGINT NOT NULL DEFAULT 0,
    cycle_shares_found BIGINT NOT NULL DEFAULT 0,
    created_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_smb_target_enabled
    ON smb_target_subnet(enabled);

CREATE TABLE IF NOT EXISTS mail_thread (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id BIGINT NOT NULL,
    host TEXT NOT NULL,
    share_id BIGINT,
    subject_tag TEXT NOT NULL,
    severity TEXT,
    status TEXT NOT NULL DEFAULT 'reported',
    recipient TEXT,
    request_message_id TEXT,
    attempt_count BIGINT NOT NULL DEFAULT 0,
    last_reason TEXT,
    retry_after DOUBLE PRECISION,
    last_error_kind TEXT,
    claimed_by BIGINT,
    claimed_at DOUBLE PRECISION,
    first_cycle_key TEXT,
    last_cycle_key TEXT,
    cycle_keys TEXT NOT NULL DEFAULT '[]',
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_mail_thread_status
    ON mail_thread(status, claimed_at);
CREATE INDEX IF NOT EXISTS idx_mail_thread_subject ON mail_thread(subject_tag);
CREATE INDEX IF NOT EXISTS idx_mail_thread_finding ON mail_thread(finding_id);

CREATE TABLE IF NOT EXISTS mail_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT,
    direction TEXT NOT NULL,
    message_id TEXT,
    in_reply_to TEXT,
    references_header TEXT,
    root_message_id TEXT,
    subject TEXT,
    subject_tag TEXT,
    mail_from TEXT,
    mail_to TEXT,
    mail_cc TEXT,
    body_excerpt TEXT,
    body_html TEXT,
    agent_verdict TEXT NOT NULL DEFAULT 'pending',
    received_at DOUBLE PRECISION NOT NULL,
    UNIQUE (message_id)
);
CREATE INDEX IF NOT EXISTS idx_mail_message_thread ON mail_message(thread_id);
CREATE INDEX IF NOT EXISTS idx_mail_message_verdict
    ON mail_message(agent_verdict, direction);
CREATE INDEX IF NOT EXISTS idx_mail_message_subject_tag ON mail_message(subject_tag);

CREATE TABLE IF NOT EXISTS mail_reply_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    message_id_pk BIGINT,
    decision TEXT NOT NULL,
    confidence DOUBLE PRECISION,
    reason TEXT,
    extracted_owner_json TEXT NOT NULL DEFAULT '{}',
    created_by TEXT,
    created_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_mail_reply_decision_thread
    ON mail_reply_decision(thread_id, created_at DESC);

CREATE TABLE IF NOT EXISTS mail_reverify_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thread_id BIGINT NOT NULL,
    finding_id BIGINT,
    share TEXT,
    path_prefix TEXT,
    verdict TEXT NOT NULL,
    access_json TEXT NOT NULL DEFAULT '{}',
    files_visible BIGINT,
    error TEXT,
    created_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_mail_reverify_result_thread
    ON mail_reverify_result(thread_id, created_at DESC);

-- P2 재귀속(2026-07-12): scan/screenshot/asset_owner 는 SMB 전용(네트워크 스윕·공유/파일 증거·owner
-- enrichment)이라 platform 에서 skill_smb 로 이동. 상호 FK 없음(standalone) → 순서 무관, 끝에 append.
CREATE TABLE IF NOT EXISTS scan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL,
    started_at DOUBLE PRECISION NOT NULL,
    finished_at DOUBLE PRECISION,
    subnets TEXT,
    alive_total BIGINT,
    accessible_total BIGINT,
    new_count BIGINT NOT NULL DEFAULT 0,
    closed_count BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_scan_kind_started ON scan(kind, started_at);

CREATE TABLE IF NOT EXISTS asset_owner (
    ip TEXT PRIMARY KEY,
    user_id TEXT,
    user_name TEXT,
    user_dept TEXT,
    email TEXT,
    source TEXT NOT NULL DEFAULT 'splunk',
    updated_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_asset_owner_user_id ON asset_owner(user_id);

CREATE TABLE IF NOT EXISTS screenshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id BIGINT NOT NULL,
    share_id BIGINT,
    file_id BIGINT,
    kind TEXT NOT NULL DEFAULT 'evidence',
    caption TEXT,
    rel_path TEXT NOT NULL,
    sha256 TEXT,
    ordinal BIGINT NOT NULL DEFAULT 1,
    created_at DOUBLE PRECISION NOT NULL,
    UNIQUE (finding_id, rel_path)
);
CREATE INDEX IF NOT EXISTS idx_screenshot_finding ON screenshot(finding_id, ordinal);
"""

# (note, ddl) 순서 고정
MIGRATIONS = [
    ('v3.60 smb_share host-level claim', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS claimed_by BIGINT'),
    ('', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS claimed_at DOUBLE PRECISION'),
    ('', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS access_modes TEXT'),
    ('', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS excluded_reason TEXT'),
    ('', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS excluded_at DOUBLE PRECISION'),
    ('', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS exception_reason TEXT'),
    ('', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS exception_thread_id BIGINT'),
    ('', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS exception_approved_by TEXT'),
    ('', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS exception_at DOUBLE PRECISION'),
    ('', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS retry_after DOUBLE PRECISION'),
    ('', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS last_error_kind TEXT'),
    ('', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS last_error TEXT'),
    ('', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS cycle_key TEXT'),
    ('', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS cycle_seen_at DOUBLE PRECISION'),
    ('', 'ALTER TABLE smb_share ADD COLUMN IF NOT EXISTS cycle_walk_done_at DOUBLE PRECISION'),
    ('smb_file_hit migration interleaved between smb_share and smb_share index blocks in source', 'ALTER TABLE smb_file_hit ADD COLUMN IF NOT EXISTS validation_json TEXT'),
    ('', 'CREATE INDEX IF NOT EXISTS idx_smb_share_claim ON smb_share(status, claimed_at)'),
    ('', 'CREATE INDEX IF NOT EXISTS idx_smb_share_retry ON smb_share(status, retry_after)'),
    ('v3.72(a) smb_target_subnet sweep progress columns', 'ALTER TABLE smb_target_subnet ADD COLUMN IF NOT EXISTS swept_at DOUBLE PRECISION'),
    ('', 'ALTER TABLE smb_target_subnet ADD COLUMN IF NOT EXISTS sweep_scan_id BIGINT'),
    ('', 'ALTER TABLE smb_target_subnet ADD COLUMN IF NOT EXISTS hosts_found BIGINT NOT NULL DEFAULT 0'),
    ('', 'ALTER TABLE smb_target_subnet ADD COLUMN IF NOT EXISTS shares_found BIGINT NOT NULL DEFAULT 0'),
    ('', 'ALTER TABLE smb_target_subnet ADD COLUMN IF NOT EXISTS claimed_by BIGINT'),
    ('', 'ALTER TABLE smb_target_subnet ADD COLUMN IF NOT EXISTS claimed_at DOUBLE PRECISION'),
    ('', 'ALTER TABLE smb_target_subnet ADD COLUMN IF NOT EXISTS cycle_key TEXT'),
    ('', 'ALTER TABLE smb_target_subnet ADD COLUMN IF NOT EXISTS cycle_swept_at DOUBLE PRECISION'),
    ('', 'ALTER TABLE smb_target_subnet ADD COLUMN IF NOT EXISTS cycle_hosts_found BIGINT NOT NULL DEFAULT 0'),
    ('', 'ALTER TABLE smb_target_subnet ADD COLUMN IF NOT EXISTS cycle_shares_found BIGINT NOT NULL DEFAULT 0'),
    ('', 'CREATE INDEX IF NOT EXISTS idx_smb_target_sweep ON smb_target_subnet(enabled, swept_at)'),
    ('', 'CREATE INDEX IF NOT EXISTS idx_smb_target_claim ON smb_target_subnet(enabled, claimed_at)'),
    ('SMB E2E mail_thread IP aggregation columns', "ALTER TABLE mail_thread ADD COLUMN IF NOT EXISTS finding_ids TEXT NOT NULL DEFAULT '[]'"),
    ('', 'ALTER TABLE mail_thread ADD COLUMN IF NOT EXISTS recurrence_count BIGINT NOT NULL DEFAULT 0'),
    ('', 'ALTER TABLE mail_thread ADD COLUMN IF NOT EXISTS first_reported_at DOUBLE PRECISION'),
    ('', 'ALTER TABLE mail_thread ADD COLUMN IF NOT EXISTS retry_after DOUBLE PRECISION'),
    ('', 'ALTER TABLE mail_thread ADD COLUMN IF NOT EXISTS last_error_kind TEXT'),
    ('', 'ALTER TABLE mail_thread ADD COLUMN IF NOT EXISTS first_cycle_key TEXT'),
    ('', 'ALTER TABLE mail_thread ADD COLUMN IF NOT EXISTS last_cycle_key TEXT'),
    ('', "ALTER TABLE mail_thread ADD COLUMN IF NOT EXISTS cycle_keys TEXT NOT NULL DEFAULT '[]'"),
    ('', 'CREATE INDEX IF NOT EXISTS idx_mail_thread_retry ON mail_thread(status, retry_after)'),
    ('drops legacy (finding_id, host) UNIQUE constraint; 7d re-sweep allows one IP to produce multiple findings', 'ALTER TABLE mail_thread DROP CONSTRAINT IF EXISTS mail_thread_finding_id_host_key'),
    ('', 'ALTER TABLE mail_message ADD COLUMN IF NOT EXISTS references_header TEXT'),
    ('', 'ALTER TABLE mail_message ADD COLUMN IF NOT EXISTS root_message_id TEXT'),
    ('', 'ALTER TABLE mail_message ADD COLUMN IF NOT EXISTS mail_cc TEXT'),
    ('', 'ALTER TABLE mail_message ADD COLUMN IF NOT EXISTS body_html TEXT'),
]

BACKFILLS = """\
-- _backfill_legacy_report_thread_cycles(c): runs the following UPDATE for each of
-- ("github_report_thread", "confluence_report_thread", "mail_thread"). Only the
-- mail_thread iteration belongs to skill_smb; the other two tables are other namespaces.
-- _LEGACY_REPORT_CYCLE_KEY = "2026-W25"; cycle_keys = json.dumps(["2026-W25"]).
UPDATE mail_thread SET first_cycle_key=?, last_cycle_key=?, cycle_keys=CASE WHEN cycle_keys IS NULL OR TRIM(cycle_keys)='' OR TRIM(cycle_keys)='[]' THEN ? ELSE cycle_keys END WHERE (first_cycle_key IS NULL OR TRIM(first_cycle_key)='') AND (last_cycle_key IS NULL OR TRIM(last_cycle_key)='')
"""

NOTES = """\
FK / ordering dependencies (baseline must run in this order): smb_credential -> smb_share (FK auth_credential_id) -> smb_directory & smb_file (FK share_id) -> smb_file_hit (FK file_id). smb_target_subnet and all mail_* tables are standalone (no FK constraints).

Cross-namespace / opaque references (NO explicit FK, so no DDL dependency but noted): smb_share.claimed_by, smb_target_subnet.claimed_by, mail_thread.claimed_by reference core chat_session ids (opaque, cross-module). mail_thread.finding_id/finding_ids, mail_reverify_result.finding_id reference the core/public findings table (opaque, no FK). mail_thread.share_id, mail_thread.exception_thread_id are BIGINT with no FK (logically point to smb_share / mail_thread). mail_message.thread_id, mail_reply_decision.thread_id, mail_reverify_result.thread_id logically point to mail_thread but have no FK.

P2 재귀속(2026-07-12): scan/screenshot/asset_owner 는 SMB 전용이라 platform→skill_smb 로 이동(위 baseline 끝에 append). 총 13테이블.
Excluded (NOT skill_smb): service_reply_message (GitHub/Confluence 공용 답장 감사) + control_flag, pipeline_heartbeat, pipeline_run, devops_target(=platform, 코어 소유) + web_target_domain, dev_web_*(=skill_dev_web) + github_*(=skill_github) + confluence_*(=skill_confluence).

idless: `asset_owner`(ip PK, id 컬럼 없음)만 skill_smb idless — IDLESS_TABLES=['asset_owner']. 나머지 12개 skill_smb 테이블은 `id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY` 보유. (control_flag/pipeline_heartbeat idless 는 platform 소유·코어 등록.)

Source-ordering quirk: in _ensure_domain_schema the smb_file_hit validation_json ALTER (line 713-715) is interleaved between the smb_share ADD COLUMN block and the smb_share CREATE INDEX block; preserved in migrations order above.

Backfill caveat: the only skill_smb backfill is the mail_thread iteration of _backfill_legacy_report_thread_cycles (verbatim UPDATE provided). _backfill_dev_web_cycles touches only dev_web_* tables (other namespace) — excluded. Both backfills sit inside the same try/except (lines 658-1061) that swallows all exceptions (permission-less ALTER ignored), so migrations+backfills are best-effort idempotent.
"""
